-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.09.2019 00:20:17
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `admin`;

--
-- Create table `history_character_mail`
--
CREATE TABLE history_character_mail (
  mailId INT(11) NOT NULL AUTO_INCREMENT,
  mailArchive TINYINT(1) NOT NULL,
  isAccountMail TINYINT(1) NOT NULL DEFAULT 0,
  recipientId BIGINT(11) NOT NULL,
  recipientName VARCHAR(255) DEFAULT NULL,
  senderId BIGINT(11) NOT NULL,
  senderName VARCHAR(255) DEFAULT NULL,
  mailRead TINYINT(1) NOT NULL,
  mailSubject VARCHAR(255) NOT NULL,
  mailMessage TEXT NOT NULL,
  currencyType INT(11) DEFAULT NULL,
  currencyAmount INT(11) DEFAULT NULL,
  currencyTaken TINYINT(1) DEFAULT 0,
  CoD TINYINT(1) NOT NULL DEFAULT 0,
  mailAttachmentItemId1Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId1 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId2Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId2 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId3Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId3 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId4Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId4 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId5Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId5 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId6Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId6 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId7Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId7 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId8Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId8 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId9Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId9 BIGINT(11) DEFAULT NULL,
  mailAttachmentItemId10Taken TINYINT(1) DEFAULT NULL,
  mailAttachmentItemId10 BIGINT(11) DEFAULT NULL,
  expiry DATETIME DEFAULT NULL,
  dateCreated TIMESTAMP NOT NULL DEFAULT '2000-01-01 06:00:00',
  dateUpdated TIMESTAMP NOT NULL DEFAULT '2000-01-01 06:00:00',
  PRIMARY KEY (mailId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `expiry` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX expiry(expiry);

--
-- Create index `isAccountMail` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX isAccountMail(isAccountMail);

--
-- Create index `isAccountMail_recipientId_mailArchive` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX isAccountMail_recipientId_mailArchive(isAccountMail, recipientId, mailArchive);

--
-- Create index `mailArchive` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX mailArchive(mailArchive);

--
-- Create index `recipientId` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX recipientId(recipientId);

--
-- Create index `recipientId_mailArchive_expiry` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX recipientId_mailArchive_expiry(recipientId, mailArchive, expiry);

--
-- Create index `senderId` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX senderId(senderId);

--
-- Create index `senderId_mailArchive_expiry` on table `character_mail`
--
ALTER TABLE character_mail 
  ADD INDEX senderId_mailArchive_expiry(senderId, mailArchive, expiry);

DELIMITER ;;

--
-- Create trigger `history_character_mail_trigger`
--
CREATE TRIGGER history_character_mail_trigger
	BEFORE UPDATE
	ON character_mail
	FOR EACH ROW
BEGIN
  IF NEW.mailArchive = 1 THEN
    INSERT INTO history_character_mail (mailId,
    mailArchive,
    isAccountMail,
    recipientId,
    recipientName,
    senderId,
    senderName,
    mailRead,
    mailSubject,
    mailMessage,
    currencyType,
    currencyAmount,
    currencyTaken,
    CoD,
    mailAttachmentItemId1Taken,
    mailAttachmentItemId1,
    mailAttachmentItemId2Taken,
    mailAttachmentItemId2,
    mailAttachmentItemId3Taken,
    mailAttachmentItemId3,
    mailAttachmentItemId4Taken,
    mailAttachmentItemId4,
    mailAttachmentItemId5Taken,
    mailAttachmentItemId5,
    mailAttachmentItemId6Taken,
    mailAttachmentItemId6,
    mailAttachmentItemId7Taken,
    mailAttachmentItemId7,
    mailAttachmentItemId8Taken,
    mailAttachmentItemId8,
    mailAttachmentItemId9Taken,
    mailAttachmentItemId9,
    mailAttachmentItemId10Taken,
    mailAttachmentItemId10,
    expiry,
    dateCreated,
    dateUpdated)
      VALUES (NEW.mailId, NEW.mailArchive, NEW.isAccountMail, NEW.recipientId, NEW.recipientName, NEW.senderId, NEW.senderName, NEW.mailRead, NEW.mailSubject, NEW.mailMessage, NEW.currencyType, NEW.currencyAmount, NEW.currencyTaken, NEW.CoD, NEW.mailAttachmentItemId1Taken, NEW.mailAttachmentItemId1, NEW.mailAttachmentItemId2Taken, NEW.mailAttachmentItemId2, NEW.mailAttachmentItemId3Taken, NEW.mailAttachmentItemId3, NEW.mailAttachmentItemId4Taken, NEW.mailAttachmentItemId4, NEW.mailAttachmentItemId5Taken, NEW.mailAttachmentItemId5, NEW.mailAttachmentItemId6Taken, NEW.mailAttachmentItemId6, NEW.mailAttachmentItemId7Taken, NEW.mailAttachmentItemId7, NEW.mailAttachmentItemId8Taken, NEW.mailAttachmentItemId8, NEW.mailAttachmentItemId9Taken, NEW.mailAttachmentItemId9, NEW.mailAttachmentItemId10Taken, NEW.mailAttachmentItemId10, NEW.expiry, NEW.dateCreated, NEW.dateUpdated);
  END IF;
END
;;

DELIMITER ;

--
-- Create column `creationtimestamp` on table `guild_rank`
--
ALTER TABLE guild_rank 
  ADD COLUMN creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

--
-- Create column `creationtimestamp` on table `guild_member`
--
ALTER TABLE guild_member 
  ADD COLUMN creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

--
-- Create column `creationtimestamp` on table `guild`
--
ALTER TABLE guild 
  ADD COLUMN creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

--
-- Create table `chat_logs`
--
CREATE TABLE chat_logs (
  id INT(11) NOT NULL AUTO_INCREMENT,
  world VARCHAR(50) NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  message VARCHAR(1024) NOT NULL,
  source BIGINT(20) NOT NULL,
  target BIGINT(20) NOT NULL,
  channel INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `character_id` on table `character_friends`
--
ALTER TABLE character_friends 
  ADD INDEX character_id(character_id);

--
-- Create index `friend_id` on table `character_friends`
--
ALTER TABLE character_friends 
  ADD INDEX friend_id(friend_id);

--
-- Create index `block_player_id` on table `character_block_list`
--
ALTER TABLE character_block_list 
  ADD INDEX block_player_id(block_player_id);

--
-- Create index `character_id` on table `character_block_list`
--
ALTER TABLE character_block_list 
  ADD INDEX character_id(character_id);

--
-- Alter column `buyout` on table `auction_house_ended`
--
ALTER TABLE auction_house_ended 
  CHANGE COLUMN buyout buyout BIGINT(20) NOT NULL;

--
-- Alter column `buyout` on table `auction_house`
--
ALTER TABLE auction_house 
  CHANGE COLUMN buyout buyout BIGINT(20) NOT NULL;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;