--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.06.2021 01:18:30
--

USE `world_content`;

--
-- Disabling DML triggers for abilities
--
DROP TRIGGER IF EXISTS abilities_trigger;

--
-- Disabling DML triggers for build_object_stage
--
DROP TRIGGER IF EXISTS build_object_stage_trigger;

--
-- Disabling DML triggers for build_object_template
--
DROP TRIGGER IF EXISTS build_object_template_trigger;

--
-- Disabling DML triggers for character_create_items
--
DROP TRIGGER IF EXISTS character_create_items_trigger;

--
-- Disabling DML triggers for character_create_skills
--
DROP TRIGGER IF EXISTS character_create_skills_trigger;

--
-- Disabling DML triggers for character_create_stats
--
DROP TRIGGER IF EXISTS character_create_stats_trigger;

--
-- Disabling DML triggers for character_create_template
--
DROP TRIGGER IF EXISTS character_create_template_trigger;

--
-- Disabling DML triggers for editor_option
--
DROP TRIGGER IF EXISTS editor_option_trigger;

--
-- Disabling DML triggers for editor_option_choice
--
DROP TRIGGER IF EXISTS editor_option_choice_trigger;

--
-- Disabling DML triggers for effects
--
DROP TRIGGER IF EXISTS effects_trigger;

--
-- Disabling DML triggers for game_setting
--
DROP TRIGGER IF EXISTS game_setting_trigger;

--
-- Disabling DML triggers for interactive_object
--
DROP TRIGGER IF EXISTS interactive_object_trigger;

--
-- Disabling DML triggers for mob_templates
--
DROP TRIGGER IF EXISTS mob_templates_trigger;

--
-- Disabling DML triggers for stat
--
DROP TRIGGER IF EXISTS stat_trigger;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- Inserting data into table character_create_stats
--
INSERT INTO character_create_stats(id, character_create_id, stat, value, levelIncrease, levelPercentIncrease, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 1, 'build_stat', 100, 0, 0, 1, '2021-06-26 16:41:06', '2021-06-26 16:41:06'),
(null, 2, 'build_stat', 100, 0, 0, 1, '2021-06-26 16:41:21', '2021-06-26 16:41:21'),
(null, 3, 'build_stat', 100, 0, 0, 1, '2021-06-26 16:41:39', '2021-06-26 16:41:39'),
(null, 4, 'build_stat', 100, 0, 0, 1, '2021-06-26 16:41:39', '2021-06-26 16:41:39'),
(null, 5, 'build_stat', 100, 0, 0, 1, '2021-06-26 16:41:39', '2021-06-26 16:41:39'),
(null, 6, 'build_stat', 100, 0, 0, 1, '2021-06-26 16:41:39', '2021-06-26 16:41:39');


--
-- Updating data of table editor_option
--
UPDATE editor_option SET deletable = 0 WHERE id = 7;
UPDATE editor_option SET deletable = 0 WHERE id = 8;
UPDATE editor_option SET deletable = 0 WHERE id = 9;
UPDATE editor_option SET deletable = 0 WHERE id = 20;
UPDATE editor_option SET deletable = 0 WHERE id = 21;
UPDATE editor_option SET deletable = 0 WHERE id = 22;

--
-- Inserting data into table editor_option
--
INSERT INTO editor_option(id, optionType, deletable, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 'Claim Type', 0, 1, '2021-06-26 12:24:56', '2021-06-26 12:27:38'),
(null, 'Claim Object Category', 0, 1, '2021-06-26 12:24:56', '2021-06-26 12:29:31');

--
-- Inserting data into table editor_option_choice
--
INSERT INTO editor_option_choice(id, optionTypeID, choice, deletable, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 10, 'Build Speed', 0, 1, '2021-06-26 15:41:28', '2021-06-26 13:42:14');

--
-- Inserting data into table game_setting
--
INSERT INTO game_setting(id, name, datatype, value, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 'USE_ABILITY_STEALTH_REDUCTION', 'int', '0', 1, '2021-06-08 01:29:52', '2021-06-08 01:29:52'),
(null, 'USE_ABILITY_STEALTH_REDUCTION_PERCENTAGE', 'float', '0', 1, '2021-06-08 01:30:12', '2021-06-08 01:30:12'),
(null, 'USE_ABILITY_STEALTH_REDUCTION_TIMEOUT', 'int', '60', 1, '2021-06-08 01:30:32', '2021-06-08 01:30:32'),
(null, 'DYNAMIC_NAVMESH_UPDATE_SAVE', 'bool', 'false', 1, '2021-06-26 20:37:57', '2021-06-26 20:37:57'),
(null, 'DYNAMIC_NAVMESH_UPDATE_INTERVAL', 'int', '1000', 1, '2021-06-26 20:38:24', '2021-06-26 20:38:24'),
(null, 'PRIVATE_INVITE_TIMEOUT', 'int', '60', 1, '2021-06-26 20:38:52', '2021-06-26 20:38:52'),
(null, 'PREFAB_LOAD_ELEMENT_LIMIT', 'int', '100', 1, '2021-06-26 20:39:23', '2021-06-26 20:39:23'),
(null, 'PVP_DAMAGE_REDUCTION_PERCENT', 'float', '0.1', 1, '2021-06-26 20:42:16', '2021-06-26 20:42:16'),
(null, 'PVP_DAMAGE_REDUCTION_USE', 'bool', 'true', 1, '2021-06-26 20:42:41', '2021-06-26 20:42:41'),
(null, 'AUTO_PAY_TAX_SYSTEM', 'bool', 'true', 1, '2021-06-26 20:53:11', '2021-06-26 18:53:53'),
(null, 'USE_TAX_SYSTEM', 'bool', 'true', 1, '2021-06-26 20:53:37', '2021-06-26 20:53:37'),
(null, 'BUILDING_CORPSE_LOOT_DURATION', 'int', '60', 1, '2021-06-26 20:54:27', '2021-06-26 20:54:27'),
(null, 'BUILDING_CORPSE_MOB_TEMPLATE', 'int', '10009', 1, '2021-06-26 20:54:51', '2021-06-26 20:54:51');

--
-- Inserting data into table stat
--
INSERT INTO stat(name, type, stat_function, mob_base, mob_level_increase, mob_level_percent_increase, min, maxstat, canExceedMax, sharedWithGroup, shiftTarget, shiftValue, shiftReverseValue, shiftInterval, isShiftPercent, onMaxHit, onMinHit, shiftReq1, shiftReq1State, shiftReq1SetReverse, shiftReq2, shiftReq2State, shiftReq2SetReverse, shiftReq3, shiftReq3State, shiftReq3SetReverse, startPercent, deathResetPercent, releaseResetPercent, sendToClient, onThreshold, onThreshold2, onThreshold3, onThreshold4, onThreshold5, threshold, threshold2, threshold3, threshold4, shiftModStat, isactive, creationtimestamp, updatetimestamp) VALUES
('build_stat', 0, 'Build Speed', 100, 0, 0, 0, '', 0, 0, 0, 0, 0, 1, 0, '', '', '', 0, 0, '', 0, 0, '', 0, 0, 50, -1, -1, 1, '', '', '', '', '', -1, -1, -1, -1, '', 1, '2021-06-26 16:34:37', '2021-06-26 16:34:37');
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

--
-- Enabling DML triggers for 
--
DELIMITER ;;

--
-- Enabling DML triggers for abilities
--
CREATE 
TRIGGER abilities_trigger
	BEFORE UPDATE
	ON abilities
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for build_object_stage
--
CREATE 
TRIGGER build_object_stage_trigger
	BEFORE UPDATE
	ON build_object_stage
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for build_object_template
--
CREATE 
TRIGGER build_object_template_trigger
	BEFORE UPDATE
	ON build_object_template
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for character_create_items
--
CREATE 
TRIGGER character_create_items_trigger
	BEFORE UPDATE
	ON character_create_items
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for character_create_skills
--
CREATE 
TRIGGER character_create_skills_trigger
	BEFORE UPDATE
	ON character_create_skills
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for character_create_stats
--
CREATE 
TRIGGER character_create_stats_trigger
	BEFORE UPDATE
	ON character_create_stats
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for character_create_template
--
CREATE 
TRIGGER character_create_template_trigger
	BEFORE UPDATE
	ON character_create_template
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for editor_option
--
CREATE 
TRIGGER editor_option_trigger
	BEFORE UPDATE
	ON editor_option
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for editor_option_choice
--
CREATE 
TRIGGER editor_option_choice_trigger
	BEFORE UPDATE
	ON editor_option_choice
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for effects
--
CREATE 
TRIGGER effects_trigger
	BEFORE UPDATE
	ON effects
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for game_setting
--
CREATE 
TRIGGER game_setting_trigger
	BEFORE UPDATE
	ON game_setting
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for interactive_object
--
CREATE 
TRIGGER interactive_object_trigger
	BEFORE UPDATE
	ON interactive_object
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for mob_templates
--
CREATE 
TRIGGER mob_templates_trigger
	BEFORE UPDATE
	ON mob_templates
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for stat
--
CREATE 
TRIGGER stat_trigger
	BEFORE UPDATE
	ON stat
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for 
--
DELIMITER ;