-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13.09.2021 22:46:36
-- Server version: 5.7.35
-- Run this script against `1040D_master` to synchronize it with dev_1050D_master
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `master`;

--
-- Create column `restriction_level` on table `world`
--
ALTER TABLE world 
  ADD COLUMN restriction_level INT(11) NOT NULL DEFAULT 0;

--
-- Change columns order on table `world`
--
ALTER TABLE world 
 MODIFY last_update TIMESTAMP NULL DEFAULT NULL AFTER restriction_level;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;