-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26.11.2019 11:38:02
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `world_content`;

--
-- Create table `vip_level_bonuses`
--
CREATE TABLE vip_level_bonuses (
  vip_level_id INT(11) NOT NULL,
  bonus_settings_id INT(11) NOT NULL,
  value INT(11) NOT NULL,
  valuep FLOAT NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `vip_level_id` on table `vip_level_bonuses`
--
ALTER TABLE vip_level_bonuses 
  ADD INDEX vip_level_id(vip_level_id, bonus_settings_id);

--
-- Create table `vip_level`
--
CREATE TABLE vip_level (
  id INT(11) NOT NULL AUTO_INCREMENT,
  level INT(11) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  max_points BIGINT(20) NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Alter column `respawnTimeMax` on table `spawn_data`
--
ALTER TABLE spawn_data 
  CHANGE COLUMN respawnTimeMax respawnTimeMax INT(11) DEFAULT NULL;

--
-- Create column `talent` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN talent TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create table `ranking_settings`
--
CREATE TABLE ranking_settings (
  id INT(11) NOT NULL AUTO_INCREMENT,
  type INT(11) NOT NULL,
  name VARCHAR(100) NOT NULL,
  count INT(11) NOT NULL,
  description VARCHAR(2048) NOT NULL,
  isactive TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create column `gear_score` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN gear_score INT(11) NOT NULL DEFAULT 0;

--
-- Create column `gear_score` on table `item_enchant_profile`
--
ALTER TABLE item_enchant_profile 
  ADD COLUMN gear_score INT(11) NOT NULL DEFAULT 0;

--
-- Create column `gear_scorep` on table `item_enchant_profile`
--
ALTER TABLE item_enchant_profile 
  ADD COLUMN gear_scorep INT(11) NOT NULL DEFAULT 0;

--
-- Create table `bonuses_settings`
--
CREATE TABLE bonuses_settings (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(65) NOT NULL,
  code VARCHAR(20) NOT NULL,
  param VARCHAR(100) NOT NULL,
  isactive TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `achievement_stats`
--
CREATE TABLE achievement_stats (
  achievement_id INT(11) NOT NULL,
  stat VARCHAR(45) NOT NULL,
  value INT(11) NOT NULL,
  valuep FLOAT NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `vip_level_id` on table `achievement_stats`
--
ALTER TABLE achievement_stats 
  ADD INDEX vip_level_id(achievement_id, stat);

--
-- Create table `achievement_settings`
--
CREATE TABLE achievement_settings (
  id INT(11) NOT NULL AUTO_INCREMENT,
  type INT(11) NOT NULL,
  value INT(11) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  objects VARCHAR(2048) NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `achievement_bonuses`
--
CREATE TABLE achievement_bonuses (
  achievement_id INT(11) NOT NULL,
  bonus_settings_id INT(11) NOT NULL,
  value INT(11) NOT NULL,
  valuep FLOAT NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `vip_level_id` on table `achievement_bonuses`
--
ALTER TABLE achievement_bonuses 
  ADD INDEX vip_level_id(achievement_id, bonus_settings_id);

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;