--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20.12.2023 22:24:28
-- Source server version: 8.0.35
-- Target server version: 8.0.35
-- 


--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE master;

--
-- Create column `queue` on table `world`
--
ALTER TABLE world 
  ADD COLUMN queue INT DEFAULT 0;

--
-- Change columns order on table `world`
--
ALTER TABLE world 
 MODIFY queue INT DEFAULT 0 AFTER max_population;

--
-- Create column `external_id` on table `account`
--
ALTER TABLE account 
  ADD COLUMN external_id VARCHAR(254) DEFAULT NULL;

--
-- Create index `externalid` on table `account`
--
ALTER TABLE account 
  ADD INDEX externalid(external_id);

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;