--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20.12.2023 22:27:15
-- Source server version: 8.0.35
-- Target server version: 8.0.35
-- 


--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE world_content;

--
-- Create column `primaryStatValue` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN primaryStatValue INT NOT NULL DEFAULT 0;

--
-- Create column `primaryStatInterval` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN primaryStatInterval INT NOT NULL DEFAULT 0;

--
-- Create column `secondaryStatValue` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN secondaryStatValue INT NOT NULL DEFAULT 0;

--
-- Create column `secondaryStatInterval` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN secondaryStatInterval INT NOT NULL DEFAULT 0;

--
-- Create column `thirdStatValue` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN thirdStatValue INT NOT NULL DEFAULT 0;

--
-- Create column `thirdStatInterval` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN thirdStatInterval INT NOT NULL DEFAULT 0;

--
-- Create column `fourthStatValue` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN fourthStatValue INT NOT NULL DEFAULT 0;

--
-- Create column `fourthStatInterval` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN fourthStatInterval INT NOT NULL DEFAULT 0;

--
-- Change columns order on table `skills`
--
ALTER TABLE skills 
 MODIFY primaryStatValue INT NOT NULL DEFAULT 0 AFTER primaryStat;
ALTER TABLE skills 
 MODIFY primaryStatInterval INT NOT NULL DEFAULT 0 AFTER primaryStatValue;
ALTER TABLE skills 
 MODIFY secondaryStatValue INT NOT NULL DEFAULT 0 AFTER secondaryStat;
ALTER TABLE skills 
 MODIFY secondaryStatInterval INT NOT NULL DEFAULT 0 AFTER secondaryStatValue;
ALTER TABLE skills 
 MODIFY thirdStatValue INT NOT NULL DEFAULT 0 AFTER thirdStat;
ALTER TABLE skills 
 MODIFY thirdStatInterval INT NOT NULL DEFAULT 0 AFTER thirdStatValue;
ALTER TABLE skills 
 MODIFY fourthStatValue INT NOT NULL DEFAULT 0 AFTER fourthStat;
ALTER TABLE skills 
 MODIFY fourthStatInterval INT NOT NULL DEFAULT 0 AFTER fourthStatValue;

--
-- Alter column `effect1value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect1value effect1value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect2value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect2value effect2value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect3value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect3value effect3value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect4value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect4value effect4value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect5value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect5value effect5value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect6value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect6value effect6value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect7value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect7value effect7value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect8value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect8value effect8value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect9value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect9value effect9value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect10value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect10value effect10value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect11value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect11value effect11value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect12value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect12value effect12value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect13value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect13value effect13value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect14value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect14value effect14value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect15value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect15value effect15value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect16value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect16value effect16value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect17value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect17value effect17value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect18value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect18value effect18value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect19value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect19value effect19value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect20value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect20value effect20value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect21value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect21value effect21value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect22value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect22value effect22value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect23value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect23value effect23value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect24value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect24value effect24value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect25value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect25value effect25value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect26value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect26value effect26value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect27value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect27value effect27value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect28value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect28value effect28value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect29value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect29value effect29value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect30value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect30value effect30value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect31value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect31value effect31value VARCHAR(86) DEFAULT '0';

--
-- Alter column `effect32value` on table `item_templates`
--
ALTER TABLE item_templates 
  CHANGE COLUMN effect32value effect32value VARCHAR(86) DEFAULT '0';

--
-- Create column `slot1` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot1 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect1` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect1 TEXT NOT NULL;

--
-- Create column `drawWeaponTime1` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime1 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect1` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect1 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime1` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime1 INT NOT NULL DEFAULT 1;

--
-- Create column `slot2` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot2 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect2` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect2 TEXT NOT NULL;

--
-- Create column `drawWeaponTime2` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime2 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect2` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect2 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime2` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime2 INT NOT NULL DEFAULT 1;

--
-- Create column `slot3` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot3 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect3` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect3 TEXT NOT NULL;

--
-- Create column `drawWeaponTime3` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime3 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect3` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect3 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime3` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime3 INT NOT NULL DEFAULT 1;

--
-- Create column `slot4` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot4 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect4` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect4 TEXT NOT NULL;

--
-- Create column `drawWeaponTime4` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime4 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect4` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect4 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime4` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime4 INT NOT NULL DEFAULT 1;

--
-- Create column `slot5` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot5 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect5` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect5 TEXT NOT NULL;

--
-- Create column `drawWeaponTime5` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime5 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect5` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect5 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime5` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime5 INT NOT NULL DEFAULT 1;

--
-- Create column `slot6` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot6 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect6` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect6 TEXT NOT NULL;

--
-- Create column `drawWeaponTime6` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime6 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect6` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect6 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime6` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime6 INT NOT NULL DEFAULT 1;

--
-- Create column `slot7` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot7 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect7` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect7 TEXT NOT NULL;

--
-- Create column `drawWeaponTime7` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime7 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect7` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect7 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime7` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime7 INT NOT NULL DEFAULT 1;

--
-- Create column `slot8` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot8 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect8` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect8 TEXT NOT NULL;

--
-- Create column `drawWeaponTime8` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime8 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect8` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect8 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime8` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime8 INT NOT NULL DEFAULT 1;

--
-- Create column `slot9` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot9 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect9` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect9 TEXT NOT NULL;

--
-- Create column `drawWeaponTime9` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime9 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect9` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect9 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime9` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime9 INT NOT NULL DEFAULT 1;

--
-- Create column `slot10` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN slot10 VARCHAR(86) NOT NULL DEFAULT '';

--
-- Create column `drawWeaponEffect10` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponEffect10 TEXT NOT NULL;

--
-- Create column `drawWeaponTime10` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN drawWeaponTime10 INT NOT NULL DEFAULT 1;

--
-- Create column `holsteringWeaponEffect10` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponEffect10 TEXT NOT NULL;

--
-- Create column `holsteringWeaponTime10` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN holsteringWeaponTime10 INT NOT NULL DEFAULT 1;

--
-- Create column `weapon_profile_id` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN weapon_profile_id INT NOT NULL DEFAULT -1;

--
-- Create column `ground_prefab` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN ground_prefab VARCHAR(128) NOT NULL DEFAULT '';

--
-- Create column `audio_profile_id` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN audio_profile_id INT NOT NULL DEFAULT -1;

--
-- Change columns order on table `item_templates`
--
ALTER TABLE item_templates 
 MODIFY slot1 VARCHAR(86) NOT NULL DEFAULT '' AFTER display;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect1 TEXT NOT NULL AFTER slot1;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime1 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect1;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect1 TEXT NOT NULL AFTER drawWeaponTime1;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime1 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect1;
ALTER TABLE item_templates 
 MODIFY slot2 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime1;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect2 TEXT NOT NULL AFTER slot2;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime2 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect2;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect2 TEXT NOT NULL AFTER drawWeaponTime2;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime2 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect2;
ALTER TABLE item_templates 
 MODIFY slot3 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime2;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect3 TEXT NOT NULL AFTER slot3;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime3 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect3;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect3 TEXT NOT NULL AFTER drawWeaponTime3;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime3 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect3;
ALTER TABLE item_templates 
 MODIFY slot4 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime3;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect4 TEXT NOT NULL AFTER slot4;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime4 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect4;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect4 TEXT NOT NULL AFTER drawWeaponTime4;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime4 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect4;
ALTER TABLE item_templates 
 MODIFY slot5 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime4;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect5 TEXT NOT NULL AFTER slot5;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime5 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect5;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect5 TEXT NOT NULL AFTER drawWeaponTime5;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime5 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect5;
ALTER TABLE item_templates 
 MODIFY slot6 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime5;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect6 TEXT NOT NULL AFTER slot6;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime6 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect6;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect6 TEXT NOT NULL AFTER drawWeaponTime6;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime6 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect6;
ALTER TABLE item_templates 
 MODIFY slot7 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime6;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect7 TEXT NOT NULL AFTER slot7;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime7 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect7;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect7 TEXT NOT NULL AFTER drawWeaponTime7;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime7 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect7;
ALTER TABLE item_templates 
 MODIFY slot8 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime7;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect8 TEXT NOT NULL AFTER slot8;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime8 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect8;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect8 TEXT NOT NULL AFTER drawWeaponTime8;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime8 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect8;
ALTER TABLE item_templates 
 MODIFY slot9 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime8;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect9 TEXT NOT NULL AFTER slot9;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime9 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect9;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect9 TEXT NOT NULL AFTER drawWeaponTime9;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime9 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect9;
ALTER TABLE item_templates 
 MODIFY slot10 VARCHAR(86) NOT NULL DEFAULT '' AFTER holsteringWeaponTime9;
ALTER TABLE item_templates 
 MODIFY drawWeaponEffect10 TEXT NOT NULL AFTER slot10;
ALTER TABLE item_templates 
 MODIFY drawWeaponTime10 INT NOT NULL DEFAULT 1 AFTER drawWeaponEffect10;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponEffect10 TEXT NOT NULL AFTER drawWeaponTime10;
ALTER TABLE item_templates 
 MODIFY holsteringWeaponTime10 INT NOT NULL DEFAULT 1 AFTER holsteringWeaponEffect10;
ALTER TABLE item_templates 
 MODIFY weapon_profile_id INT NOT NULL DEFAULT -1 AFTER enchant_profile_id;
ALTER TABLE item_templates 
 MODIFY ground_prefab VARCHAR(128) NOT NULL DEFAULT '' AFTER repairable;
ALTER TABLE item_templates 
 MODIFY audio_profile_id INT NOT NULL DEFAULT -1 AFTER ground_prefab;

--
-- Create column `dodge` on table `character_create_template`
--
ALTER TABLE character_create_template 
  ADD COLUMN dodge INT NOT NULL DEFAULT -1;

--
-- Create column `attack_time` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN attack_time FLOAT NOT NULL DEFAULT 0;

--
-- Create column `targetSubType` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN targetSubType VARCHAR(64) NOT NULL DEFAULT '';

--
-- Create column `casterState` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN casterState INT NOT NULL DEFAULT 1;

--
-- Create column `stealth_reduction_amount` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN stealth_reduction_amount INT NOT NULL DEFAULT 0;

--
-- Create column `stealth_reduction_percentage` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN stealth_reduction_percentage FLOAT NOT NULL DEFAULT 0;

--
-- Create column `stealth_reduction_timeout` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN stealth_reduction_timeout BIGINT NOT NULL DEFAULT 0;

--
-- Create column `skill_up_chance` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN skill_up_chance INT NOT NULL DEFAULT 0;

--
-- Create column `miss_chance` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN miss_chance FLOAT NOT NULL DEFAULT 0.05;

--
-- Create column `tags_on_caster` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN tags_on_caster TEXT NOT NULL;

--
-- Create column `tags_on_target` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN tags_on_target TEXT NOT NULL;

--
-- Create column `tags_not_on_caster` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN tags_not_on_caster TEXT NOT NULL;

--
-- Create column `tags_not_on_target` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN tags_not_on_target TEXT NOT NULL;

--
-- Create column `pulse_tags_on_caster` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN pulse_tags_on_caster TEXT NOT NULL;

--
-- Create column `pulse_tags_on_target` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN pulse_tags_on_target TEXT NOT NULL;

--
-- Create column `pulse_tags_not_on_caster` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN pulse_tags_not_on_caster TEXT NOT NULL;

--
-- Create column `is_child` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN is_child TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create column `combatState` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN combatState INT NOT NULL DEFAULT 2;

--
-- Create column `powerUpCoordEffect` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN powerUpCoordEffect VARCHAR(128) NOT NULL DEFAULT '';

--
-- Create column `makeBusy` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN makeBusy TINYINT(1) NOT NULL DEFAULT 1;

--
-- Create column `checkBusy` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN checkBusy TINYINT(1) NOT NULL DEFAULT 1;

--
-- Create column `weaponMustBeDrawn` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN weaponMustBeDrawn TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create column `drawnWeaponBefore` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN drawnWeaponBefore TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create column `enemyTargetChangeToSelf` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN enemyTargetChangeToSelf TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create column `line_of_sight` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN line_of_sight TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create column `pulse_tags_not_on_target` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN pulse_tags_not_on_target TEXT NOT NULL;

--
-- Change columns order on table `abilities`
--
ALTER TABLE abilities 
 MODIFY attack_time FLOAT NOT NULL DEFAULT 0 AFTER activationLength;
ALTER TABLE abilities 
 MODIFY targetSubType VARCHAR(64) NOT NULL DEFAULT '' AFTER targetType;
ALTER TABLE abilities 
 MODIFY casterState INT NOT NULL DEFAULT 1 AFTER targetState;
ALTER TABLE abilities 
 MODIFY isactive TINYINT(1) DEFAULT 1 AFTER pulse_tags_not_on_target;
ALTER TABLE abilities 
 MODIFY creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER isactive;
ALTER TABLE abilities 
 MODIFY updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00' AFTER creationtimestamp;

--
-- Create table `weapon_templates_profile`
--
CREATE TABLE weapon_templates_profile (
	  id INT NOT NULL AUTO_INCREMENT,
	  name VARCHAR(86) DEFAULT NULL,
	  isactive TINYINT(1) DEFAULT 1,
	  creationtimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  updatetimestamp DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `weapon_action_settings`
--
CREATE TABLE weapon_action_settings (
	  id INT NOT NULL AUTO_INCREMENT,
	  profile_id INT NOT NULL DEFAULT 1,
	  action_id INT DEFAULT NULL,
	  slot VARCHAR(256) DEFAULT '',
	  ability_id INT DEFAULT -1,
	  action_type INT DEFAULT 1,
	  coordeffect VARCHAR(256) DEFAULT NULL,
	  isactive TINYINT(1) DEFAULT 1,
	  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
	  PRIMARY KEY (id, profile_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `item_slots_sets`
--
CREATE TABLE item_slots_sets (
	  id INT NOT NULL AUTO_INCREMENT,
	  slot_id INT DEFAULT NULL,
	  set_id INT DEFAULT NULL,
	  race INT DEFAULT NULL,
	  class INT DEFAULT NULL,
	  creationtimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  updatetimestamp DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `slot_id` on table `item_slots_sets`
--
ALTER TABLE item_slots_sets 
  ADD INDEX slot_id(slot_id);

--
-- Create table `item_audio_profile`
--
CREATE TABLE item_audio_profile (
	  id INT NOT NULL AUTO_INCREMENT,
	  name VARCHAR(68) NOT NULL DEFAULT '',
	  use_event VARCHAR(256) NOT NULL DEFAULT '',
	  drag_begin_event VARCHAR(256) NOT NULL DEFAULT '',
	  drag_end_event VARCHAR(256) NOT NULL DEFAULT '',
	  delete_event VARCHAR(256) NOT NULL DEFAULT '',
	  broke_event VARCHAR(256) NOT NULL DEFAULT '',
	  pick_up_event VARCHAR(256) NOT NULL DEFAULT '',
	  fall_event VARCHAR(256) NOT NULL DEFAULT '',
	  drop_event VARCHAR(256) NOT NULL DEFAULT '',
	  isactive TINYINT(1) DEFAULT 1,
	  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `ability_effects`
--
CREATE TABLE ability_effects (
	  id INT NOT NULL AUTO_INCREMENT,
	  ability_power_id INT NOT NULL,
	  target VARCHAR(64) NOT NULL,
	  effect INT NOT NULL,
	  delay INT NOT NULL,
	  chance_min FLOAT NOT NULL,
	  chance_max FLOAT NOT NULL,
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `ability_id` on table `ability_effects`
--
ALTER TABLE ability_effects 
  ADD INDEX ability_id(ability_power_id);

--
-- Create table `ability_combos`
--
CREATE TABLE ability_combos (
	  id INT NOT NULL AUTO_INCREMENT,
	  ability_parent_id INT NOT NULL,
	  ability_sub_id INT NOT NULL,
	  chance_min FLOAT NOT NULL DEFAULT 0,
	  chance_max FLOAT NOT NULL DEFAULT 100,
	  show_in_center_ui TINYINT(1) NOT NULL DEFAULT 1,
	  replace_in_slot TINYINT(1) NOT NULL DEFAULT 1,
	  check_cooldown TINYINT(1) NOT NULL DEFAULT 1,
	  time INT NOT NULL,
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `ability_parent_id` on table `ability_combos`
--
ALTER TABLE ability_combos 
  ADD INDEX ability_parent_id(ability_parent_id);

--
-- Create table `ability_abilities`
--
CREATE TABLE ability_abilities (
	  id INT NOT NULL AUTO_INCREMENT,
	  ability_power_id INT NOT NULL,
	  target VARCHAR(64) NOT NULL,
	  ability INT NOT NULL,
	  delay INT NOT NULL,
	  chance_min FLOAT NOT NULL,
	  chance_max FLOAT NOT NULL,
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `ability_id` on table `ability_abilities`
--
ALTER TABLE ability_abilities 
  ADD INDEX ability_id(ability_power_id);

--
-- Create table `abilities_triggers_profile`
--
CREATE TABLE abilities_triggers_profile (
	  id INT NOT NULL AUTO_INCREMENT,
	  name VARCHAR(64) NOT NULL,
	  event_type INT NOT NULL,
	  tags TEXT NOT NULL,
	  race INT NOT NULL DEFAULT -1,
	  class INT NOT NULL DEFAULT -1,
	  action_type TINYINT NOT NULL,
	  chance_min FLOAT NOT NULL DEFAULT 0,
	  chance_max FLOAT NOT NULL DEFAULT 100,
	  isactive TINYINT(1) NOT NULL DEFAULT 1,
	  creationtimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  updatetimestamp DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `abilities_triggers_actions`
--
CREATE TABLE abilities_triggers_actions (
	  id INT NOT NULL AUTO_INCREMENT,
	  abilities_triggers_id INT NOT NULL,
	  target INT NOT NULL,
	  ability INT NOT NULL,
	  effect INT NOT NULL,
	  mod_v INT NOT NULL DEFAULT 0,
	  mod_p FLOAT NOT NULL DEFAULT 0,
	  chance_min FLOAT NOT NULL,
	  chance_max FLOAT NOT NULL,
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `abilities_triggers`
--
CREATE TABLE abilities_triggers (
	  id INT NOT NULL AUTO_INCREMENT,
	  ability_power_id INT NOT NULL DEFAULT -1,
	  trigger_id INT NOT NULL DEFAULT -1,
	  creationtimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  updatetimestamp DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `abilities_powerup_settings`
--
CREATE TABLE abilities_powerup_settings (
	  id INT NOT NULL AUTO_INCREMENT,
	  ability_id INT DEFAULT NULL,
	  thresholdMaxTime FLOAT NOT NULL,
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `ability_id` on table `abilities_powerup_settings`
--
ALTER TABLE abilities_powerup_settings 
  ADD INDEX ability_id(ability_id);

--
-- Create table `abilities_coordeffects`
--
CREATE TABLE abilities_coordeffects (
	  id INT NOT NULL AUTO_INCREMENT,
	  ability_power_id INT DEFAULT NULL,
	  coordEffectEvent VARCHAR(64) NOT NULL DEFAULT '',
	  coordEffect VARCHAR(128) NOT NULL DEFAULT '',
	  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create index `abilityPowerId` on table `abilities_coordeffects`
--
ALTER TABLE abilities_coordeffects 
  ADD INDEX abilityPowerId(ability_power_id);

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
