--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20.12.2023 22:43:28
-- Source server version: 8.0.35
-- Target server version: 8.0.35
--

SET NAMES 'utf8';

USE world_content;

--
-- Disabling DML triggers for `character_create_stats`
--
DROP TRIGGER IF EXISTS character_create_stats_trigger;

--
-- Disabling DML triggers for `character_create_template`
--
DROP TRIGGER IF EXISTS character_create_template_trigger;

--
-- Disabling DML triggers for `editor_option`
--
DROP TRIGGER IF EXISTS editor_option_trigger;

--
-- Disabling DML triggers for `editor_option_choice`
--
DROP TRIGGER IF EXISTS editor_option_choice_trigger;

--
-- Disabling DML triggers for `game_setting`
--
DROP TRIGGER IF EXISTS game_setting_trigger;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;


--
-- Inserting data into table `editor_option`
--
INSERT INTO editor_option(id, optionType, deletable, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 'Target Sub Type', 0, 1, '2023-10-06 13:55:02', '2000-01-01 00:00:00'),
(null, 'Slots Sets', 0, 1, '2023-10-18 19:24:03', '2023-11-10 19:48:33'),
(null, 'Weapon Actions', 0, 1, '2023-11-13 23:25:19', '2023-11-17 21:43:19');

--
-- Updating data of table `editor_option_choice`
--
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `optionTypeID` = (SELECT id FROM `editor_option` where `optionType` = 'Target Sub Type') Where `choice` = "Self";
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `optionTypeID` = (SELECT id FROM `editor_option` where `optionType` = 'Target Sub Type') Where `choice` = "Friendly";
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `optionTypeID` = (SELECT id FROM `editor_option` where `optionType` = 'Target Sub Type') Where `choice` = "Friend Not Self";
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `optionTypeID` = (SELECT id FROM `editor_option` where `optionType` = 'Target Sub Type') Where `choice` = "Enemy";
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `choice` = 'Single Target' Where `choice` = "AoE Enemy";
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `choice` = 'AoE' Where `choice` = "AoE Friendly";
UPDATE `editor_option_choice` SET `updatetimestamp` = CURRENT_TIMESTAMP, `choice` = 'Location(Trap)' Where `choice` = "Self Location";


--
-- Inserting data into table `editor_option_choice`
--
INSERT INTO editor_option_choice(id, optionTypeID, choice, deletable, isactive, creationtimestamp, updatetimestamp) VALUES
(null, (SELECT id FROM `editor_option` where `optionType` = 'Target Sub Type'), 'Friendly or Enemy', 0, 1, '2023-10-06 13:55:02', '2000-01-01 00:00:00'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Slots Sets'), 'Set 1', 1, 1, '2023-11-10 20:48:34', '2023-11-10 20:48:34'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Slots Sets'), 'Set 2', 1, 1, '2023-11-10 20:48:34', '2023-11-10 20:48:34'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Weapon Actions'), 'Action1', 1, 1, '2023-11-14 00:31:35', '2023-11-17 21:43:19'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Weapon Actions'), 'Action2', 1, 1, '2023-11-15 19:29:01', '2023-11-17 21:43:19'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Weapon Actions'), 'Action3', 1, 1, '2023-11-16 01:34:44', '2023-11-17 21:43:20'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Weapon Actions'), 'Action4', 1, 1, '2023-11-16 01:34:59', '2023-11-17 21:43:20'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Weapon Actions'), 'Action5', 1, 1, '2023-11-16 01:35:12', '2023-11-17 21:43:20'),
(null, (SELECT id FROM `editor_option` where `optionType` = 'Item Quality'), 'Coins', 1, 1, '2023-12-16 23:28:05', '2023-12-16 23:28:05');

--
-- Updating data of table `game_setting`
--
UPDATE game_setting SET isactive = 0, updatetimestamp = '2023-12-17 20:45:56' WHERE name = 'SKILL_PRIMARY_STAT_GAIN_INCREMENT';
UPDATE game_setting SET isactive = 0, updatetimestamp = '2023-12-17 20:45:57' WHERE name = 'SKILL_SECONDARY_STAT_GAIN_INCREMENT';
UPDATE game_setting SET isactive = 0, updatetimestamp = '2023-12-17 20:45:58' WHERE name = 'SKILL_THIRD_STAT_GAIN_INCREMENT';
UPDATE game_setting SET isactive = 0, updatetimestamp = '2023-12-17 20:45:55' WHERE name = 'SKILL_FOURTH_STAT_GAIN_INCREMENT';

--
-- Inserting data into table `game_setting`
--
INSERT INTO game_setting(id, name, datatype, value, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 'PREFAB_MAX_INCOMING_MESSAGE_LENGTH', 'int', '500000', 1, '2023-09-04 20:33:23', '2000-01-01 00:00:00'),
(null, 'LOGIN_QUEUE_MAX_INTERVAL', 'int', '5000', 1, '2023-11-10 20:47:05', '2023-11-10 20:47:05'),
(null, 'LOGIN_QUEUE_MAX_USERS', 'int', '2', 1, '2023-11-10 20:47:56', '2023-11-10 20:47:56'),
(null, 'LOGIN_QUEUE_RATE', 'float', '0.1', 1, '2023-11-10 20:48:15', '2023-11-10 20:03:37'),
(null, 'INVENTORY_LOOT_ON_GROUND', 'bool', 'true', 1, '2023-12-10 19:39:17', '2023-12-10 19:39:17'),
(null, 'INVENTORY_LOOT_ON_GROUND_TIMEOUT', 'int', '600', 1, '2023-12-12 19:11:30', '2023-12-12 19:11:30'),
(null, 'INVENTORY_LOOT_ON_GROUND_TIMEOUT_INTERVAL', 'int', '5', 1, '2023-12-12 19:11:59', '2023-12-17 20:26:48'),
(null, 'INVENTORY_LOOT_ON_GROUND_MAX_DISTANCE', 'int', '10', 1, '2023-12-14 14:17:56', '2023-12-14 14:17:56'),
(null, 'INVENTORY_LOOT_ON_GROUND_LOGOUT_QUALITY_MAIL', 'string', '5;6', 1, '2023-12-14 16:52:13', '2023-12-16 22:49:01');


UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Friend Not Self' Where `targetType` = 'Friend Not Self';
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Self' Where `targetType` = 'Self' or `targetType` = "Self Location";
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Friendly' Where `targetType` = 'Group';
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Enemy' Where `targetType` = 'Enemy';
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Enemy' Where `targetType` = 'AoE Enemy';
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Friendly' Where `targetType` = 'Friendly';
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetSubType` = 'Friendly' Where `targetType` = 'AoE Friendly';

UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetType` = 'AoE' Where `targetType` = 'AoE Friendly' or `targetType` = 'AoE Enemy';
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetType` = 'Single Target' Where `targetType` = 'Enemy' or `targetType` = 'Friendly' or `targetType` = 'Self' or `targetType` = 'Friend Not Self' ;
UPDATE `abilities` SET `updatetimestamp` = CURRENT_TIMESTAMP, `targetType` = 'Location(Trap)' Where `targetType` = 'Self Location';
--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

DELIMITER ;;

--
-- Enabling DML triggers for `character_create_stats`
--
CREATE 
TRIGGER character_create_stats_trigger
	BEFORE UPDATE
	ON character_create_stats
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for `character_create_template`
--
CREATE 
TRIGGER character_create_template_trigger
	BEFORE UPDATE
	ON character_create_template
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for `editor_option`
--
CREATE 
TRIGGER editor_option_trigger
	BEFORE UPDATE
	ON editor_option
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for `editor_option_choice`
--
CREATE 
TRIGGER editor_option_choice_trigger
	BEFORE UPDATE
	ON editor_option_choice
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for `game_setting`
--
CREATE 
TRIGGER game_setting_trigger
	BEFORE UPDATE
	ON game_setting
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

DELIMITER ;