--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.11.2019 22:04:58
--



SET NAMES 'utf8';
USE `world_content`;

--
-- Disabling DML triggers for editor_option_choice
--
DROP TRIGGER IF EXISTS editor_option_choice_trigger;

--
-- Disabling DML triggers for game_setting
--
DROP TRIGGER IF EXISTS game_setting_trigger;

--
-- Disabling DML triggers for item_templates
--
DROP TRIGGER IF EXISTS item_templates_trigger;

--
-- Disabling DML triggers for item_templates_options
--
DROP TRIGGER IF EXISTS item_templates_options_trigger;

--
-- Disabling DML triggers for skills
--
DROP TRIGGER IF EXISTS skills_trigger;

--
-- Disabling DML triggers for skill_ability_gain
--
DROP TRIGGER IF EXISTS skill_ability_gain_trigger;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Updating data of table editor_option_choice
--
UPDATE editor_option_choice SET updatetimestamp = '2019-11-24 00:18:16' WHERE id = 36;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-24 00:18:16' WHERE id = 37;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-24 00:18:16' WHERE id = 38;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 57;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 58;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 59;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 64;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 65;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 66;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 72;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 73;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-13 09:52:57' WHERE id = 80;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 95;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 101;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 102;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 108;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 130;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 131;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 132;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 141;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 142;

--
-- Inserting data into table editor_option_choice
--
INSERT INTO editor_option_choice(id, optionTypeID, choice, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 12, 'VipPoints', 1, '2019-10-08 16:29:02', '2019-11-20 16:55:28'),
(null, 12, 'VipTime', 1, '2019-10-08 16:29:02', '2019-11-20 16:55:28'),
(null, 12, 'Bonus', 1, '2019-10-22 13:17:47', '2019-11-20 16:55:28'),
(null, 17, 'asdasd', 1, '2019-11-13 09:52:47', '2019-11-13 09:53:08'),
(null, 12, 'SkillPoints', 1, '2019-11-16 11:27:12', '2019-11-20 16:55:28'),
(null, 12, 'TalentPoints', 1, '2019-11-16 11:27:12', '2019-11-20 16:55:28'),
(null, 12, 'SkillReset', 1, '2019-11-18 17:57:15', '2019-11-20 16:55:28'),
(null, 12, 'TalentReset', 1, '2019-11-18 17:57:15', '2019-11-20 16:55:28'),
(null, 12, 'Achievement', 1, '2019-11-20 16:55:28', '2000-01-01 00:00:00'),
(null, 8, 'Repair', 1, '2019-11-24 00:18:16', '2000-01-01 00:00:00');

--
-- Deleting data from table game_setting
--
DELETE FROM game_setting WHERE id IN(40, 114, 115);

--
-- Updating data of table game_setting
--
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 10:43:51' WHERE id = 4;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 10:43:55' WHERE id = 5;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 10:44:04' WHERE id = 6;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:00:59' WHERE id = 7;
UPDATE game_setting SET value = 'true', updatetimestamp = '2019-11-19 16:22:48' WHERE id = 8;
UPDATE game_setting SET updatetimestamp = '2019-10-02 15:54:24' WHERE id = 14;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 11:09:09' WHERE id = 28;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:01:17' WHERE id = 29;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:12:00' WHERE id = 31;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:12:51' WHERE id = 32;
UPDATE game_setting SET value = '1', updatetimestamp = '2019-11-26 11:24:41' WHERE id = 50;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:01:45' WHERE id = 53;
UPDATE game_setting SET datatype = 'int', value = '75', updatetimestamp = '2019-11-26 11:26:50' WHERE id = 54;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:01:55' WHERE id = 55;
UPDATE game_setting SET datatype = 'float', value = '2', updatetimestamp = '2019-11-26 11:29:56' WHERE id = 56;
UPDATE game_setting SET value = '1.5', updatetimestamp = '2019-11-26 11:31:48' WHERE id = 58;
UPDATE game_setting SET value = '2.5', updatetimestamp = '2019-11-26 11:31:54' WHERE id = 59;
UPDATE game_setting SET value = '4', updatetimestamp = '2019-11-26 11:34:04' WHERE id = 62;
UPDATE game_setting SET value = '5', updatetimestamp = '2019-11-26 11:34:12' WHERE id = 63;
UPDATE game_setting SET value = '6', updatetimestamp = '2019-11-26 11:34:22' WHERE id = 64;
UPDATE game_setting SET value = '7', updatetimestamp = '2019-11-26 11:34:33' WHERE id = 65;
UPDATE game_setting SET datatype = 'int ', updatetimestamp = '2019-11-26 11:35:07' WHERE id = 66;
UPDATE game_setting SET datatype = 'int', isactive = 0, updatetimestamp = '2019-11-26 11:36:17' WHERE id = 67;
UPDATE game_setting SET datatype = 'int', value = '600', updatetimestamp = '2019-11-26 11:42:24' WHERE id = 72;
UPDATE game_setting SET datatype = 'bool', updatetimestamp = '2019-11-26 11:42:44' WHERE id = 73;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 11:43:25' WHERE id = 75;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 11:43:43' WHERE id = 76;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:44:03' WHERE id = 77;
UPDATE game_setting SET datatype = 'bool', updatetimestamp = '2019-11-26 11:44:30' WHERE id = 78;
UPDATE game_setting SET updatetimestamp = '2019-11-26 11:44:57' WHERE id = 79;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:46:05' WHERE id = 85;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:46:42' WHERE id = 87;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:48:57' WHERE id = 94;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:59:14' WHERE id = 107;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 12:00:13' WHERE id = 108;
UPDATE game_setting SET value = '0', updatetimestamp = '2019-11-26 12:01:08' WHERE id = 109;
UPDATE game_setting SET datatype = 'bool', value = 'false', updatetimestamp = '2019-11-26 12:02:19' WHERE id = 111;
UPDATE game_setting SET datatype = 'bool', value = 'false', updatetimestamp = '2019-11-26 12:02:23' WHERE id = 112;
UPDATE game_setting SET datatype = 'int', value = '10', updatetimestamp = '2019-11-26 12:03:05' WHERE id = 113;

--
-- Inserting data into table game_setting
--
INSERT INTO game_setting(id, name, datatype, value, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 'DEATH_PERMANENTLY', 'bool', 'false', 1, '2019-10-06 21:09:59', '2019-11-26 12:04:15'),
(null, 'COLLECTION_SAVE_INTERVAL', 'int', '60', 1, '2019-11-16 00:15:51', '2000-01-01 00:00:00'),
(null, 'RANKING_CALCULATION_INTERVAL', 'int', '1440', 1, '2019-11-16 00:16:32', '2019-11-26 12:04:52'),
(null, 'USE_TALENT_PURCHASE_POINTS', 'bool', 'true', 1, '2019-11-19 16:23:35', '2000-01-01 00:00:00'),
(null, 'TALENT_POINTS_GIVEN_PER_LEVEL', 'int', '3', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'SOCKET_RESET_CHANCE', 'float', '60', 1, '2018-11-14 00:16:07', '2019-11-26 11:48:57'),
(null, 'LOOT_FOR_ALL', 'bool', 'false', 1, '2019-08-21 10:29:25', '2019-11-26 12:02:23'),
(null, 'COLLECTION_SAVE_INTERVAL', 'int', '60', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'DEATH_LOST_EXP', 'bool', 'false', 1, '2019-08-21 10:29:25', '2019-11-26 12:02:23'),
(null, 'DEATH_LOST_EXP_PERCENTAGE', 'float', '10', 1, '2018-11-14 00:16:07', '2019-11-26 11:48:57'),
(null, 'LOST_LEVEL', 'bool', 'false', 1, '2019-08-21 10:29:25', '2019-11-26 12:02:23'),
(null, 'LOOT_DICE_TIMEOUT', 'int', '30', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'GROUP_LOOT_DEFAULT_ROLL', 'int', '0', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'GROUP_LOOT_DEFAULT_DICE', 'int', '0', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'GROUP_LOOT_DEFAULT_GRADE', 'int', '3', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00');

--
-- Updating data of table item_templates
--
UPDATE item_templates SET effect15type = 'Durability', effect15value = '100', updatetimestamp = '2019-11-26 12:29:47' WHERE id = 20001;
UPDATE item_templates SET effect15type = 'Durability', effect15value = '100', updatetimestamp = '2019-11-26 12:31:06' WHERE id = 20002;
UPDATE item_templates SET effect15type = 'Durability', effect15value = '100', updatetimestamp = '2019-11-26 12:30:34' WHERE id = 20003;
UPDATE item_templates SET effect13type = 'Durability', effect13name = '', effect13value = '200', effect14type = '', effect14name = '', effect14value = '', effect15type = '', effect15name = '', effect15value = '', effect16type = '', effect16name = '', effect16value = '', effect17type = '', effect17name = '', effect17value = '', effect18type = '', effect18name = '', effect18value = '', effect19type = '', effect19name = '', effect19value = '', effect20type = '', effect20name = '', effect20value = '', effect21type = '', effect21name = '', effect21value = '', effect22type = '', effect22name = '', effect22value = '', effect23type = '', effect23name = '', effect23value = '', effect24type = '', effect24name = '', effect24value = '', effect25type = '', effect25name = '', effect25value = '', effect26type = '', effect26name = '', effect26value = '', effect27type = '', effect27name = '', effect27value = '', effect28type = '', effect28name = '', effect28value = '', effect29type = '', effect29name = '', effect29value = '', effect30type = '', effect30name = '', effect30value = '', effect31type = '', effect31name = '', effect31value = '', effect32type = '', effect32name = '', effect32value = '', updatetimestamp = '2019-11-26 12:30:15' WHERE id = 20004;
UPDATE item_templates SET effect13type = 'Durability', effect13name = '', effect13value = '200', effect14type = '', effect14name = '', effect14value = '', effect15type = '', effect15name = '', effect15value = '', effect16type = '', effect16name = '', effect16value = '', effect17type = '', effect17name = '', effect17value = '', effect18type = '', effect18name = '', effect18value = '', effect19type = '', effect19name = '', effect19value = '', effect20type = '', effect20name = '', effect20value = '', effect21type = '', effect21name = '', effect21value = '', effect22type = '', effect22name = '', effect22value = '', effect23type = '', effect23name = '', effect23value = '', effect24type = '', effect24name = '', effect24value = '', effect25type = '', effect25name = '', effect25value = '', effect26type = '', effect26name = '', effect26value = '', effect27type = '', effect27name = '', effect27value = '', effect28type = '', effect28name = '', effect28value = '', effect29type = '', effect29name = '', effect29value = '', effect30type = '', effect30name = '', effect30value = '', effect31type = '', effect31name = '', effect31value = '', effect32type = '', effect32name = '', effect32value = '', updatetimestamp = '2019-11-26 12:31:21' WHERE id = 20005;
UPDATE item_templates SET effect13type = 'Durability', effect13name = '', effect13value = '200', effect14type = '', effect14name = '', effect14value = '', effect15type = '', effect15name = '', effect15value = '', effect16type = '', effect16name = '', effect16value = '', effect17type = '', effect17name = '', effect17value = '', effect18type = '', effect18name = '', effect18value = '', effect19type = '', effect19name = '', effect19value = '', effect20type = '', effect20name = '', effect20value = '', effect21type = '', effect21name = '', effect21value = '', effect22type = '', effect22name = '', effect22value = '', effect23type = '', effect23name = '', effect23value = '', effect24type = '', effect24name = '', effect24value = '', effect25type = '', effect25name = '', effect25value = '', effect26type = '', effect26name = '', effect26value = '', effect27type = '', effect27name = '', effect27value = '', effect28type = '', effect28name = '', effect28value = '', effect29type = '', effect29name = '', effect29value = '', effect30type = '', effect30name = '', effect30value = '', effect31type = '', effect31name = '', effect31value = '', effect32type = '', effect32name = '', effect32value = '', updatetimestamp = '2019-11-26 12:30:51' WHERE id = 20006;

--
-- Inserting data into table item_templates
--
INSERT INTO item_templates(id, name, icon, category, subcategory, itemType, subType, slot, display, itemQuality, binding, isUnique, stackLimit, duration, purchaseCurrency, purchaseCost, sellable, damage, damageMax, damageType, delay, toolTip, triggerEvent, triggerAction1Type, triggerAction1Data, effect1type, effect1name, effect1value, effect2type, effect2name, effect2value, effect3type, effect3name, effect3value, effect4type, effect4name, effect4value, effect5type, effect5name, effect5value, effect6type, effect6name, effect6value, effect7type, effect7name, effect7value, effect8type, effect8name, effect8value, effect9type, effect9name, effect9value, effect10type, effect10name, effect10value, effect11type, effect11name, effect11value, effect12type, effect12name, effect12value, effect13type, effect13name, effect13value, effect14type, effect14name, effect14value, effect15type, effect15name, effect15value, effect16type, effect16name, effect16value, effect17type, effect17name, effect17value, effect18type, effect18name, effect18value, effect19type, effect19name, effect19value, effect20type, effect20name, effect20value, effect21type, effect21name, effect21value, effect22type, effect22name, effect22value, effect23type, effect23name, effect23value, effect24type, effect24name, effect24value, effect25type, effect25name, effect25value, effect26type, effect26name, effect26value, effect27type, effect27name, effect27value, effect28type, effect28name, effect28value, effect29type, effect29name, effect29value, effect30type, effect30name, effect30value, effect31type, effect31name, effect31value, effect32type, effect32name, effect32value, isactive, creationtimestamp, updatetimestamp, actionBarAllowed, enchant_profile_id, auctionHouse, skillExp) VALUES
(null, 'VIP Point I', 'Assets/Dragonsan/AtavismObjects/Icons/Custom/VIP.png', '0', '0', 'Consumable', '', '', '', 4, 0, 0, 100, NULL, 4, 10, 0, 0, 0, '', 1.5, 'This item will give you 100 VIP Points, to increase your VIP Level.', NULL, NULL, NULL, 'VipPoints', '', '100', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:33:24', '2019-11-26 12:55:16', 0, -1, 0, 1),
(null, 'VIP Point II', 'Assets/Dragonsan/AtavismObjects/Icons/Custom/VIP.png', '0', '0', 'Consumable', '', '', '', 5, 0, 0, 100, NULL, 4, 15, 0, 0, 0, '', 1.5, 'This item will give you 200 VIP Points, to increase your VIP Level.', NULL, NULL, NULL, 'VipPoints', '', '200', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:33:32', '2019-11-26 12:55:23', 0, -1, 0, 1),
(null, 'VIP Point III', 'Assets/Dragonsan/AtavismObjects/Icons/Custom/VIP.png', '0', '0', 'Consumable', '', '', '', 6, 0, 0, 100, NULL, 4, 30, 0, 0, 0, '', 1.5, 'This item will give you 500 VIP Points, to increase your VIP Level.', NULL, NULL, NULL, 'VipPoints', '', '500', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:33:57', '2019-11-26 12:55:29', 0, -1, 0, 1),
(null, 'VIP Time I', 'Assets/Dragonsan/AtavismObjects/Icons/Custom/VIP.png', '0', '0', 'Consumable', '', '', '', 4, 0, 0, 100, NULL, 4, 5, 0, 0, 0, '', 1.5, 'This item will add 5 minutes to your VIP.', NULL, NULL, NULL, 'VipTime', '', '5', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:34:45', '2019-11-26 12:55:35', 0, -1, 0, 1),
(null, 'VIP Time II', 'Assets/Dragonsan/AtavismObjects/Icons/Custom/VIP.png', '0', '0', 'Consumable', '', '', '', 5, 0, 0, 100, NULL, 4, 15, 0, 0, 0, '', 1.5, 'This item will add 30 minutes to your VIP.', NULL, NULL, NULL, 'VipTime', '', '30', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:35:35', '2019-11-26 12:55:40', 0, -1, 0, 1),
(null, 'VIP Time III', 'Assets/Dragonsan/AtavismObjects/Icons/Custom/VIP.png', '0', '0', 'Consumable', '', '', '', 6, 0, 0, 100, NULL, 4, 30, 0, 0, 0, '', 1.5, 'This item will add 2 hours to your VIP.', NULL, NULL, NULL, 'VipTime', '', '120', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:35:54', '2019-11-26 12:55:46', 0, -1, 0, 1),
(null, 'Skill Point Item', 'Assets/Dragonsan/AtavismObjects/Textures/OldUI/Hud/MENU_Skills.png', '0', '0', 'Consumable', '', '', '', 3, 0, 0, 1, NULL, 3, 5, 1, 0, 0, '', 1.5, 'Learn additional skill point.', NULL, NULL, NULL, 'SkillPoints', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:39:03', '2019-11-26 12:56:06', 0, -1, 0, 1),
(null, 'Talent Point Item', 'Assets/Dragonsan/AtavismObjects/Textures/OldUI/Hud/MENU_Skills.png', '0', '0', 'Consumable', '', '', '', 3, 0, 0, 1, NULL, 3, 5, 1, 0, 0, '', 1.5, 'Learn additional talent point.', NULL, NULL, NULL, 'TalentPoints', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:51:33', '2019-11-26 12:56:12', 0, -1, 0, 1),
(null, 'Skill Points Reset', 'Assets/Dragonsan/UGUIMiniMap for Atavism/Content/Art/UI/Icons/Icon_Atlas.png', '0', '0', 'Consumable', '', '', '', 3, 0, 0, 1, NULL, 3, 5, 1, 0, 0, '', 1.5, 'Reset your skill points.', NULL, NULL, NULL, 'SkillReset', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:52:31', '2019-11-26 12:56:19', 0, -1, 0, 1),
(null, 'Talent Points Reset', 'Assets/Dragonsan/UGUIMiniMap for Atavism/Content/Art/UI/Icons/Icon_Atlas.png', '0', '0', 'Consumable', '', '', '', 3, 0, 0, 1, NULL, 3, 5, 1, 0, 0, '', 1.5, 'Reset your talent points.', NULL, NULL, NULL, 'TalentReset', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:53:18', '2019-11-26 12:56:25', 0, -1, 0, 1),
(null, 'Achievement Item', 'Assets/Dragonsan/UGUIMiniMap for Atavism/Content/Art/UI/Icons/Icon_Atlas.png', '0', '0', 'Consumable', '', '', '', 4, 0, 0, 1, NULL, 3, 5, 1, 0, 0, '', 1.5, 'Complete Bomber Bug Queen Exterminator Achievement.', NULL, NULL, NULL, 'Achievement', '', '3', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, '2019-11-26 12:53:45', '2019-11-26 12:54:59', 0, -1, 0, 1);

--
-- Updating data of table item_templates_options
--
UPDATE item_templates_options SET updatetimestamp = '2019-11-26 12:30:15' WHERE id = 2;
UPDATE item_templates_options SET updatetimestamp = '2019-11-26 12:31:21' WHERE id = 3;
UPDATE item_templates_options SET updatetimestamp = '2019-11-26 12:30:51' WHERE id = 4;

--
-- Inserting data into table skills
--
INSERT INTO skills(id, name, icon, aspect, oppositeAspect, mainAspectOnly, primaryStat, secondaryStat, thirdStat, fourthStat, maxLevel, automaticallyLearn, skillPointCost, parentSkill, parentSkillLevelReq, prereqSkill1, prereqSkill1Level, prereqSkill2, prereqSkill2Level, prereqSkill3, prereqSkill3Level, playerLevelReq, skill_profile_id, type, isactive, creationtimestamp, updatetimestamp) VALUES
(15, 'Talent example I', 'Assets/OtherPackages/[MiDaEm]/Magic Weapon Icons/Variation A/Weapon_10.png', -1, -1, 0, 'dexterity', '~ none ~', '~ none ~', '~ none ~', 10, 0, 1, -1, 0, -1, 0, -1, 0, -1, 0, 0, -1, 1, 1, '2019-11-26 12:57:07', '2019-11-26 14:23:37'),
(16, 'Talent example II', 'Assets/OtherPackages/[MiDaEm]/Magic Weapon Icons/Weapon_10.png', -1, -1, 0, 'dexterity', '~ none ~', '~ none ~', '~ none ~', 10, 0, 1, 15, 5, -1, 0, -1, 0, -1, 0, 0, -1, 1, 1, '2019-11-26 12:59:01', '2019-11-26 14:23:46'),
(17, 'Talent example III', 'Assets/OtherPackages/[MiDaEm]/Magic Weapon Icons/Variation C/Weapon_10.png', -1, -1, 0, 'dexterity', '~ none ~', '~ none ~', '~ none ~', 10, 0, 1, 16, 5, -1, 0, -1, 0, -1, 0, 0, -1, 1, 1, '2019-11-26 12:59:22', '2019-11-26 14:23:52');

--
-- Inserting data into table skill_ability_gain
--
INSERT INTO skill_ability_gain(id, skillID, skillLevelReq, abilityID, automaticallyLearn, isactive, creationtimestamp, updatetimestamp) VALUES
(70, 15, 1, 23, 1, 0, '2019-11-26 12:57:07', '2019-11-26 12:58:56'),
(71, 15, 1, 29, 1, 0, '2019-11-26 12:57:07', '2019-11-26 12:58:56');
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

--
-- Enabling DML triggers for 
--
DELIMITER ;;

--
-- Enabling DML triggers for editor_option_choice
--
CREATE 
TRIGGER editor_option_choice_trigger
	BEFORE UPDATE
	ON editor_option_choice
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for game_setting
--
CREATE 
TRIGGER game_setting_trigger
	BEFORE UPDATE
	ON game_setting
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for item_templates
--
CREATE 
TRIGGER item_templates_trigger
	BEFORE UPDATE
	ON item_templates
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for item_templates_options
--
CREATE 
TRIGGER item_templates_options_trigger
	BEFORE UPDATE
	ON item_templates_options
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for skills
--
CREATE 
TRIGGER skills_trigger
	BEFORE UPDATE
	ON skills
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for skill_ability_gain
--
CREATE 
TRIGGER skill_ability_gain_trigger
	BEFORE UPDATE
	ON skill_ability_gain
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for 
--
DELIMITER ;