--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25.07.2018 21:49:35
--



SET NAMES 'utf8';
USE `world_content`;

--
-- Disabling DML triggers for editor_option_choice
--
DROP TRIGGER IF EXISTS editor_option_choice_trigger;

--
-- Disabling DML triggers for game_setting
--
DROP TRIGGER IF EXISTS game_setting_trigger;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Inserting data into table editor_option_choice
--
INSERT INTO editor_option_choice(id, optionTypeID, choice, isactive, creationtimestamp, updatetimestamp) VALUES
(NULL, 12, 'DeathLossChance', 1, '2018-07-20 23:56:34', '2000-01-01 00:00:00');

--
-- Inserting data into table game_setting
--
INSERT INTO game_setting(id, name, datatype, value, isactive, creationtimestamp, updatetimestamp) VALUES
(NULL, 'PLAYER_SILENCE_TIMEOUT', '', '30', 1, '2018-07-20 23:30:33', '2000-01-01 00:00:00'),
(NULL, 'DISTANCE_REQ_BETWEEN_CLAIMS', '', '10', 1, '2018-07-20 23:30:50', '2000-01-01 00:00:00'),
(NULL, 'PET_DISTANCE_DESPAWN', '', '50', 1, '2018-07-20 23:31:07', '2018-07-20 23:32:27'),
(NULL, 'MOB_FORCE_DESPAWN_IN_COMBAT', '', 'false', 1, '2018-07-20 23:31:26', '2018-07-20 23:32:08');
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

--
-- Enabling DML triggers for 
--
DELIMITER ;;

--
-- Enabling DML triggers for editor_option_choice
--
CREATE 
	DEFINER = 'root'@'localhost'
TRIGGER editor_option_choice_trigger
	BEFORE UPDATE
	ON editor_option_choice
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for game_setting
--
CREATE 
	DEFINER = 'root'@'localhost'
TRIGGER game_setting_trigger
	BEFORE UPDATE
	ON game_setting
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for 
--
DELIMITER ;