--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.11.2019 22:04:58
--



SET NAMES 'utf8';
USE `world_content`;

--
-- Disabling DML triggers for editor_option_choice
--
DROP TRIGGER IF EXISTS editor_option_choice_trigger;

--
-- Disabling DML triggers for game_setting
--
DROP TRIGGER IF EXISTS game_setting_trigger;

--
-- Disabling DML triggers for item_templates
--
DROP TRIGGER IF EXISTS item_templates_trigger;

--
-- Disabling DML triggers for item_templates_options
--
DROP TRIGGER IF EXISTS item_templates_options_trigger;

--
-- Disabling DML triggers for skills
--
DROP TRIGGER IF EXISTS skills_trigger;

--
-- Disabling DML triggers for skill_ability_gain
--
DROP TRIGGER IF EXISTS skill_ability_gain_trigger;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Updating data of table editor_option_choice
--
UPDATE editor_option_choice SET updatetimestamp = '2019-11-24 00:18:16' WHERE id = 36;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-24 00:18:16' WHERE id = 37;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-24 00:18:16' WHERE id = 38;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 57;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 58;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 59;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 64;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 65;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 66;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 72;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 73;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-13 09:52:57' WHERE id = 80;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 95;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 101;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 102;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:27' WHERE id = 108;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 130;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 131;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 132;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 141;
UPDATE editor_option_choice SET updatetimestamp = '2019-11-20 16:55:28' WHERE id = 142;

--
-- Inserting data into table editor_option_choice
--
INSERT INTO editor_option_choice(id, optionTypeID, choice, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 12, 'VipPoints', 1, '2019-10-08 16:29:02', '2019-11-20 16:55:28'),
(null, 12, 'VipTime', 1, '2019-10-08 16:29:02', '2019-11-20 16:55:28'),
(null, 12, 'Bonus', 1, '2019-10-22 13:17:47', '2019-11-20 16:55:28'),
(null, 17, 'asdasd', 1, '2019-11-13 09:52:47', '2019-11-13 09:53:08'),
(null, 12, 'SkillPoints', 1, '2019-11-16 11:27:12', '2019-11-20 16:55:28'),
(null, 12, 'TalentPoints', 1, '2019-11-16 11:27:12', '2019-11-20 16:55:28'),
(null, 12, 'SkillReset', 1, '2019-11-18 17:57:15', '2019-11-20 16:55:28'),
(null, 12, 'TalentReset', 1, '2019-11-18 17:57:15', '2019-11-20 16:55:28'),
(null, 12, 'Achievement', 1, '2019-11-20 16:55:28', '2000-01-01 00:00:00'),
(null, 8, 'Repair', 1, '2019-11-24 00:18:16', '2000-01-01 00:00:00');

--
-- Deleting data from table game_setting
--
DELETE FROM game_setting WHERE id IN(40, 114, 115);

--
-- Updating data of table game_setting
--
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 10:43:51' WHERE id = 4;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 10:43:55' WHERE id = 5;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 10:44:04' WHERE id = 6;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:00:59' WHERE id = 7;
UPDATE game_setting SET value = 'true', updatetimestamp = '2019-11-19 16:22:48' WHERE id = 8;
UPDATE game_setting SET updatetimestamp = '2019-10-02 15:54:24' WHERE id = 14;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 11:09:09' WHERE id = 28;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:01:17' WHERE id = 29;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:12:00' WHERE id = 31;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:12:51' WHERE id = 32;
UPDATE game_setting SET value = '1', updatetimestamp = '2019-11-26 11:24:41' WHERE id = 50;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:01:45' WHERE id = 53;
UPDATE game_setting SET datatype = 'int', value = '75', updatetimestamp = '2019-11-26 11:26:50' WHERE id = 54;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-17 19:01:55' WHERE id = 55;
UPDATE game_setting SET datatype = 'float', value = '2', updatetimestamp = '2019-11-26 11:29:56' WHERE id = 56;
UPDATE game_setting SET value = '1.5', updatetimestamp = '2019-11-26 11:31:48' WHERE id = 58;
UPDATE game_setting SET value = '2.5', updatetimestamp = '2019-11-26 11:31:54' WHERE id = 59;
UPDATE game_setting SET value = '4', updatetimestamp = '2019-11-26 11:34:04' WHERE id = 62;
UPDATE game_setting SET value = '5', updatetimestamp = '2019-11-26 11:34:12' WHERE id = 63;
UPDATE game_setting SET value = '6', updatetimestamp = '2019-11-26 11:34:22' WHERE id = 64;
UPDATE game_setting SET value = '7', updatetimestamp = '2019-11-26 11:34:33' WHERE id = 65;
UPDATE game_setting SET datatype = 'int ', updatetimestamp = '2019-11-26 11:35:07' WHERE id = 66;
UPDATE game_setting SET datatype = 'int', isactive = 0, updatetimestamp = '2019-11-26 11:36:17' WHERE id = 67;
UPDATE game_setting SET datatype = 'int', value = '600', updatetimestamp = '2019-11-26 11:42:24' WHERE id = 72;
UPDATE game_setting SET datatype = 'bool', updatetimestamp = '2019-11-26 11:42:44' WHERE id = 73;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 11:43:25' WHERE id = 75;
UPDATE game_setting SET datatype = 'int', updatetimestamp = '2019-11-26 11:43:43' WHERE id = 76;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:44:03' WHERE id = 77;
UPDATE game_setting SET datatype = 'bool', updatetimestamp = '2019-11-26 11:44:30' WHERE id = 78;
UPDATE game_setting SET updatetimestamp = '2019-11-26 11:44:57' WHERE id = 79;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:46:05' WHERE id = 85;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:46:42' WHERE id = 87;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:48:57' WHERE id = 94;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 11:59:14' WHERE id = 107;
UPDATE game_setting SET datatype = 'float', updatetimestamp = '2019-11-26 12:00:13' WHERE id = 108;
UPDATE game_setting SET value = '0', updatetimestamp = '2019-11-26 12:01:08' WHERE id = 109;
UPDATE game_setting SET datatype = 'bool', value = 'false', updatetimestamp = '2019-11-26 12:02:19' WHERE id = 111;
UPDATE game_setting SET datatype = 'bool', value = 'false', updatetimestamp = '2019-11-26 12:02:23' WHERE id = 112;
UPDATE game_setting SET datatype = 'int', value = '10', updatetimestamp = '2019-11-26 12:03:05' WHERE id = 113;

--
-- Inserting data into table game_setting
--
INSERT INTO game_setting(id, name, datatype, value, isactive, creationtimestamp, updatetimestamp) VALUES
(null, 'DEATH_PERMANENTLY', 'bool', 'false', 1, '2019-10-06 21:09:59', '2019-11-26 12:04:15'),
(null, 'COLLECTION_SAVE_INTERVAL', 'int', '60', 1, '2019-11-16 00:15:51', '2000-01-01 00:00:00'),
(null, 'RANKING_CALCULATION_INTERVAL', 'int', '1440', 1, '2019-11-16 00:16:32', '2019-11-26 12:04:52'),
(null, 'USE_TALENT_PURCHASE_POINTS', 'bool', 'true', 1, '2019-11-19 16:23:35', '2000-01-01 00:00:00'),
(null, 'TALENT_POINTS_GIVEN_PER_LEVEL', 'int', '3', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'SOCKET_RESET_CHANCE', 'float', '60', 1, '2018-11-14 00:16:07', '2019-11-26 11:48:57'),
(null, 'LOOT_FOR_ALL', 'bool', 'false', 1, '2019-08-21 10:29:25', '2019-11-26 12:02:23'),
(null, 'COLLECTION_SAVE_INTERVAL', 'int', '60', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'DEATH_LOST_EXP', 'bool', 'false', 1, '2019-08-21 10:29:25', '2019-11-26 12:02:23'),
(null, 'DEATH_LOST_EXP_PERCENTAGE', 'float', '10', 1, '2018-11-14 00:16:07', '2019-11-26 11:48:57'),
(null, 'LOST_LEVEL', 'bool', 'false', 1, '2019-08-21 10:29:25', '2019-11-26 12:02:23'),
(null, 'LOOT_DICE_TIMEOUT', 'int', '30', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'GROUP_LOOT_DEFAULT_ROLL', 'int', '0', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'GROUP_LOOT_DEFAULT_DICE', 'int', '0', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00'),
(null, 'GROUP_LOOT_DEFAULT_GRADE', 'int', '3', 1, '2019-11-19 16:23:52', '2000-01-01 00:00:00');

-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

--
-- Enabling DML triggers for 
--
DELIMITER ;;

--
-- Enabling DML triggers for editor_option_choice
--
CREATE 
TRIGGER editor_option_choice_trigger
	BEFORE UPDATE
	ON editor_option_choice
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for game_setting
--
CREATE 
TRIGGER game_setting_trigger
	BEFORE UPDATE
	ON game_setting
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for item_templates
--
CREATE 
TRIGGER item_templates_trigger
	BEFORE UPDATE
	ON item_templates
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for item_templates_options
--
CREATE 
TRIGGER item_templates_options_trigger
	BEFORE UPDATE
	ON item_templates_options
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for skills
--
CREATE 
TRIGGER skills_trigger
	BEFORE UPDATE
	ON skills
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for skill_ability_gain
--
CREATE 
TRIGGER skill_ability_gain_trigger
	BEFORE UPDATE
	ON skill_ability_gain
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for 
--
DELIMITER ;