--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20.12.2023 23:17:56
-- Source server version: 8.0.35
-- Target server version: 8.0.35
--

SET NAMES 'utf8';

USE atavism;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Inserting data into table `oid_manager`
--
INSERT INTO oid_manager(token, free_oid) VALUES
(2, 1);

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
