-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13.04.2019 21:02:52
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `admin`;

--
-- Alter column `locX` on table `island_portals`
--
ALTER TABLE island_portals 
  CHANGE COLUMN locX locX DECIMAL(65, 2) NOT NULL;

--
-- Alter column `locY` on table `island_portals`
--
ALTER TABLE island_portals 
  CHANGE COLUMN locY locY DECIMAL(65, 2) NOT NULL;

--
-- Alter column `locZ` on table `island_portals`
--
ALTER TABLE island_portals 
  CHANGE COLUMN locZ locZ DECIMAL(65, 2) NOT NULL;

--
-- Create column `parent` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN parent INT(11) NOT NULL DEFAULT -1;

--
-- Create column `permanent` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN permanent TINYINT(1) NOT NULL DEFAULT 0;

--
-- Create column `org_cost` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN org_cost INT(11) NOT NULL;

--
-- Create column `org_currency` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN org_currency INT(11) NOT NULL;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;