-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.09.2019 00:20:41
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `atavism`;

--
-- Create index `type_name` on table `objstore`
--
ALTER TABLE objstore 
  ADD INDEX type_name(type, name);

--
-- Create index `world_name_instance_namespace_int` on table `objstore`
--
ALTER TABLE objstore 
  ADD INDEX world_name_instance_namespace_int(world_name, instance, namespace_int);

--
-- Create index `world_name_namespace_int_name` on table `objstore`
--
ALTER TABLE objstore 
  ADD INDEX world_name_namespace_int_name(world_name, namespace_int, name);

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;