-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.09.2019 00:18:33
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `world_content`;

--
-- Create column `mobTemplate2` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN mobTemplate2 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `mobTemplate3` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN mobTemplate3 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `mobTemplate4` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN mobTemplate4 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `mobTemplate5` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN mobTemplate5 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `respawnTimeMax` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN respawnTimeMax INT(11) NOT NULL;

--
-- Create column `alternateSpawnMobTemplate2` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN alternateSpawnMobTemplate2 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `alternateSpawnMobTemplate3` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN alternateSpawnMobTemplate3 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `alternateSpawnMobTemplate4` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN alternateSpawnMobTemplate4 INT(11) NOT NULL DEFAULT -1;

--
-- Create column `alternateSpawnMobTemplate5` on table `spawn_data`
--
ALTER TABLE spawn_data 
  ADD COLUMN alternateSpawnMobTemplate5 INT(11) NOT NULL DEFAULT -1;

--
-- Change columns order on table `spawn_data`
--
ALTER TABLE spawn_data 
 MODIFY mobTemplate2 INT(11) NOT NULL DEFAULT -1 AFTER mobTemplate;
ALTER TABLE spawn_data 
 MODIFY mobTemplate3 INT(11) NOT NULL DEFAULT -1 AFTER mobTemplate2;
ALTER TABLE spawn_data 
 MODIFY mobTemplate4 INT(11) NOT NULL DEFAULT -1 AFTER mobTemplate3;
ALTER TABLE spawn_data 
 MODIFY mobTemplate5 INT(11) NOT NULL DEFAULT -1 AFTER mobTemplate4;
ALTER TABLE spawn_data 
 MODIFY respawnTimeMax INT(11) NOT NULL AFTER respawnTime;
ALTER TABLE spawn_data 
 MODIFY alternateSpawnMobTemplate2 INT(11) NOT NULL DEFAULT -1 AFTER alternateSpawnMobTemplate;
ALTER TABLE spawn_data 
 MODIFY alternateSpawnMobTemplate3 INT(11) NOT NULL DEFAULT -1 AFTER alternateSpawnMobTemplate2;
ALTER TABLE spawn_data 
 MODIFY alternateSpawnMobTemplate4 INT(11) NOT NULL DEFAULT -1 AFTER alternateSpawnMobTemplate3;
ALTER TABLE spawn_data 
 MODIFY alternateSpawnMobTemplate5 INT(11) NOT NULL DEFAULT -1 AFTER alternateSpawnMobTemplate4;

--
-- Create column `skinningLevelMax` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN skinningLevelMax INT(11) NOT NULL DEFAULT 0;

--
-- Create column `skinningSkillId` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN skinningSkillId INT(11) NOT NULL DEFAULT -1;

--
-- Create column `skinningSkillExp` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN skinningSkillExp INT(11) NOT NULL DEFAULT 0;

--
-- Create column `skinningWeaponReq` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN skinningWeaponReq VARCHAR(200) NOT NULL DEFAULT '';

--
-- Create column `skinningHarvestTime` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN skinningHarvestTime DECIMAL(20, 1) NOT NULL DEFAULT 2.0;

--
-- Change columns order on table `mob_templates`
--
ALTER TABLE mob_templates 
 MODIFY skinningLevelMax INT(11) NOT NULL DEFAULT 0 AFTER skinningLevelReq;
ALTER TABLE mob_templates 
 MODIFY skinningSkillId INT(11) NOT NULL DEFAULT -1 AFTER skinningLevelMax;
ALTER TABLE mob_templates 
 MODIFY skinningSkillExp INT(11) NOT NULL DEFAULT 0 AFTER skinningSkillId;
ALTER TABLE mob_templates 
 MODIFY skinningWeaponReq VARCHAR(200) NOT NULL DEFAULT '' AFTER skinningSkillExp;
ALTER TABLE mob_templates 
 MODIFY skinningHarvestTime DECIMAL(20, 1) NOT NULL DEFAULT 2.0 AFTER skinningWeaponReq;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;