-- 
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.108.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14.11.2018 00:34:42
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `admin`;

--
-- Create table `history_auction_house_ended`
--
CREATE TABLE history_auction_house_ended (
  id BIGINT(11) NOT NULL AUTO_INCREMENT,
  auction_id BIGINT(11) NOT NULL,
  startbid INT(11) NOT NULL,
  currency_id INT(3) NOT NULL,
  expire_date DATETIME NOT NULL,
  auctioneer_oid BIGINT(20) NOT NULL,
  owner_oid BIGINT(20) NOT NULL,
  bidder_oid BIGINT(20) NOT NULL,
  race_group_id INT(11) NOT NULL,
  bid INT(11) NOT NULL,
  buyout INT(11) NOT NULL,
  status INT(2) NOT NULL,
  mode INT(2) NOT NULL,
  item_oid BIGINT(20) NOT NULL,
  item_count INT(11) NOT NULL,
  item_template_id INT(11) NOT NULL,
  item_enchant_level INT(11) NOT NULL,
  item_sockets_info TEXT NOT NULL,
  world_name VARCHAR(64) NOT NULL,
  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `expire_date` on table `history_auction_house_ended`
--
ALTER TABLE history_auction_house_ended 
  ADD INDEX expire_date(expire_date);

DELIMITER ;;

--
-- Create trigger `history_auction_house_ended_trigger`
--
CREATE TRIGGER history_auction_house_ended_trigger
	BEFORE UPDATE
	ON history_auction_house_ended
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

DELIMITER ;

--
-- Create table `character_block_list`
--
CREATE TABLE character_block_list (
  id INT(11) NOT NULL AUTO_INCREMENT,
  character_id BIGINT(20) NOT NULL,
  block_player_id BIGINT(20) NOT NULL,
  friend_name VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `auction_house_ended`
--
CREATE TABLE auction_house_ended (
  id BIGINT(11) NOT NULL AUTO_INCREMENT,
  startbid INT(11) NOT NULL,
  currency_id INT(3) NOT NULL,
  expire_date DATETIME NOT NULL,
  auctioneer_oid BIGINT(20) NOT NULL,
  owner_oid BIGINT(20) NOT NULL,
  bidder_oid BIGINT(20) NOT NULL,
  race_group_id INT(11) NOT NULL,
  bid INT(11) NOT NULL,
  buyout INT(11) NOT NULL,
  status INT(2) NOT NULL,
  mode INT(2) NOT NULL,
  item_oid BIGINT(20) NOT NULL,
  item_count INT(11) NOT NULL,
  item_template_id INT(11) NOT NULL,
  item_enchant_level INT(11) NOT NULL,
  item_sockets_info TEXT NOT NULL,
  world_name VARCHAR(64) NOT NULL,
  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `expire_date` on table `auction_house_ended`
--
ALTER TABLE auction_house_ended 
  ADD INDEX expire_date(expire_date);

DELIMITER ;;

--
-- Create trigger `history_auction_house_ended`
--
CREATE TRIGGER history_auction_house_ended
	BEFORE UPDATE
	ON auction_house_ended
	FOR EACH ROW
BEGIN
  IF NEW.status = 7 THEN
    INSERT INTO history_auction_house_ended (
    auction_id,
    startbid,
    currency_id,
    expire_date,
    auctioneer_oid,
    owner_oid,
    bidder_oid,
    race_group_id,
    bid,
    buyout,
    status,
    mode,
    item_oid,
    item_count,
    item_template_id,
    item_enchant_level,
    item_sockets_info,
    world_name,
    creationtimestamp,
    updatetimestamp)
      VALUES (NEW.id, NEW.startbid, NEW.currency_id, NEW.expire_date, NEW.auctioneer_oid, NEW.owner_oid, NEW.bidder_oid, NEW.race_group_id, NEW.bid, NEW.buyout, NEW.status, NEW.mode, NEW.item_oid, NEW.item_count, NEW.item_template_id, NEW.item_enchant_level, NEW.item_sockets_info, NEW.world_name, NEW.creationtimestamp, NEW.updatetimestamp);
  END IF;
END
;;

DELIMITER ;

--
-- Create table `auction_house`
--
CREATE TABLE auction_house (
  id INT(11) NOT NULL AUTO_INCREMENT,
  startbid INT(11) NOT NULL,
  currency_id INT(3) NOT NULL,
  expire_date DATETIME NOT NULL,
  auctioneer_oid BIGINT(20) NOT NULL,
  owner_oid BIGINT(20) NOT NULL,
  bidder_oid BIGINT(20) NOT NULL,
  race_group_id INT(11) NOT NULL,
  bid INT(11) NOT NULL,
  buyout INT(11) NOT NULL,
  status INT(2) NOT NULL,
  mode INT(2) NOT NULL,
  item_oid BIGINT(20) NOT NULL,
  item_count INT(11) NOT NULL,
  item_template_id INT(11) NOT NULL,
  item_enchant_level INT(11) NOT NULL,
  item_sockets_info TEXT NOT NULL,
  world_name VARCHAR(64) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `expire_date` on table `auction_house`
--
ALTER TABLE auction_house 
  ADD INDEX expire_date(expire_date);

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;