-- 
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.108.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14.11.2018 00:37:24
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `atavism`;

--
-- Create table `player_item_sockets`
--
CREATE TABLE player_item_sockets (
  item_oid BIGINT(20) NOT NULL,
  socket_item_id BIGINT(20) NOT NULL DEFAULT 0,
  socket_id SMALLINT(6) NOT NULL,
  world_name VARCHAR(64) NOT NULL,
  PRIMARY KEY (socket_id, world_name, item_oid)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `player_items`
--
CREATE TABLE player_items (
  obj_id BIGINT(20) NOT NULL,
  templateID INT(11) NOT NULL,
  stackSize INT(11) NOT NULL DEFAULT 1,
  `inv.backref` INT(11) NOT NULL,
  persistenceFlag TINYINT(4) NOT NULL,
  item_equipInfo VARCHAR(20) DEFAULT NULL,
  world_name VARCHAR(64) NOT NULL,
  enchant_level INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (obj_id, world_name)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;