-- 
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.108.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14.11.2018 00:38:35

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `world_content`;

--
-- Create table `skill_profile_levels`
--
CREATE TABLE skill_profile_levels (
  id INT(11) NOT NULL AUTO_INCREMENT,
  profile_id INT(11) NOT NULL,
  level INT(11) NOT NULL,
  required_xp INT(11) NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
ROW_FORMAT = COMPACT;

--
-- Create table `skill_profile`
--
CREATE TABLE skill_profile (
  id INT(11) NOT NULL AUTO_INCREMENT,
  profile_name VARCHAR(64) NOT NULL,
  level_diff TEXT NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
ROW_FORMAT = COMPACT;

--
-- Create column `skill_profile_id` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN skill_profile_id INT(11) NOT NULL;

--
-- Change columns order on table `skills`
--
ALTER TABLE skills 
 MODIFY skill_profile_id INT(11) NOT NULL AFTER playerLevelReq;

--
-- Create column `effect13type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect13type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect13name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect13name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect13value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect13value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect14type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect14type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect14name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect14name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect14value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect14value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect15type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect15type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect15name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect15name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect15value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect15value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect16type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect16type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect16name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect16name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect16value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect16value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect17type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect17type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect17name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect17name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect17value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect17value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect18type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect18type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect18name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect18name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect18value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect18value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect19type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect19type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect19name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect19name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect19value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect19value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect20type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect20type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect20name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect20name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect20value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect20value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect21type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect21type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect21name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect21name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect21value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect21value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect22type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect22type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect22name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect22name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect22value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect22value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect23type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect23type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect23name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect23name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect23value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect23value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect24type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect24type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect24name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect24name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect24value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect24value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect25type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect25type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect25name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect25name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect25value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect25value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect26type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect26type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect26name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect26name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect26value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect26value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect27type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect27type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect27name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect27name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect27value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect27value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect28type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect28type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect28name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect28name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect28value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect28value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect29type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect29type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect29name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect29name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect29value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect29value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect30type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect30type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect30name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect30name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect30value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect30value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect31type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect31type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect31name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect31name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect31value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect31value VARCHAR(256) DEFAULT '0';

--
-- Create column `effect32type` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect32type VARCHAR(32) DEFAULT NULL;

--
-- Create column `effect32name` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect32name VARCHAR(45) DEFAULT NULL;

--
-- Create column `effect32value` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN effect32value VARCHAR(256) DEFAULT '0';

--
-- Create column `enchant_profile_id` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN enchant_profile_id INT(11) NOT NULL DEFAULT -1;

--
-- Create column `auctionHouse` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN auctionHouse TINYINT(1) NOT NULL DEFAULT 1;

--
-- Change columns order on table `item_templates`
--
ALTER TABLE item_templates 
 MODIFY isactive TINYINT(1) DEFAULT 1 AFTER effect32value;
ALTER TABLE item_templates 
 MODIFY creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER isactive;
ALTER TABLE item_templates 
 MODIFY updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00' AFTER creationtimestamp;
ALTER TABLE item_templates 
 MODIFY actionBarAllowed TINYINT(1) NOT NULL DEFAULT 0 AFTER updatetimestamp;

--
-- Create table `item_set_profile`
--
CREATE TABLE item_set_profile (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  isactive TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `item_set_level`
--
CREATE TABLE item_set_level (
  id INT(11) NOT NULL AUTO_INCREMENT,
  set_id INT(11) NOT NULL,
  number_of_parts INT(11) NOT NULL,
  damage INT(11) DEFAULT 0,
  damagep INT(11) DEFAULT 0,
  effect1valuep INT(11) DEFAULT 0,
  effect1name VARCHAR(45) DEFAULT NULL,
  effect1value INT(11) DEFAULT 0,
  effect2valuep INT(11) DEFAULT 0,
  effect2name VARCHAR(45) DEFAULT NULL,
  effect2value INT(11) DEFAULT 0,
  effect3valuep INT(11) DEFAULT 0,
  effect3name VARCHAR(45) DEFAULT NULL,
  effect3value INT(11) DEFAULT 0,
  effect4valuep INT(11) DEFAULT 0,
  effect4name VARCHAR(45) DEFAULT NULL,
  effect4value INT(11) DEFAULT 0,
  effect5valuep INT(11) DEFAULT 0,
  effect5name VARCHAR(45) DEFAULT NULL,
  effect5value INT(11) DEFAULT 0,
  effect6valuep INT(11) DEFAULT 0,
  effect6name VARCHAR(45) DEFAULT NULL,
  effect6value INT(11) DEFAULT 0,
  effect7valuep INT(11) DEFAULT 0,
  effect7name VARCHAR(45) DEFAULT NULL,
  effect7value INT(11) DEFAULT 0,
  effect8valuep INT(11) DEFAULT 0,
  effect8name VARCHAR(45) DEFAULT NULL,
  effect8value INT(11) DEFAULT 0,
  effect9valuep INT(11) DEFAULT 0,
  effect9name VARCHAR(45) DEFAULT NULL,
  effect9value INT(11) DEFAULT 0,
  effect10valuep INT(11) DEFAULT 0,
  effect10name VARCHAR(45) DEFAULT NULL,
  effect10value INT(11) DEFAULT 0,
  effect11valuep INT(11) DEFAULT 0,
  effect11name VARCHAR(45) DEFAULT NULL,
  effect11value INT(11) DEFAULT 0,
  effect12valuep INT(11) DEFAULT 0,
  effect12name VARCHAR(45) DEFAULT NULL,
  effect12value INT(11) DEFAULT 0,
  effect13valuep INT(11) DEFAULT 0,
  effect13name VARCHAR(45) DEFAULT NULL,
  effect13value INT(11) DEFAULT 0,
  effect14valuep INT(11) DEFAULT 0,
  effect14name VARCHAR(45) DEFAULT NULL,
  effect14value INT(11) DEFAULT 0,
  effect15valuep INT(11) DEFAULT 0,
  effect15name VARCHAR(45) DEFAULT NULL,
  effect15value INT(11) DEFAULT 0,
  effect16valuep INT(11) DEFAULT 0,
  effect16name VARCHAR(45) DEFAULT NULL,
  effect16value INT(11) DEFAULT 0,
  effect17valuep INT(11) DEFAULT 0,
  effect17name VARCHAR(45) DEFAULT NULL,
  effect17value INT(11) DEFAULT 0,
  effect18valuep INT(11) DEFAULT 0,
  effect18name VARCHAR(45) DEFAULT NULL,
  effect18value INT(11) DEFAULT 0,
  effect19valuep INT(11) DEFAULT 0,
  effect19name VARCHAR(45) DEFAULT NULL,
  effect19value INT(11) DEFAULT 0,
  effect20valuep INT(11) DEFAULT 0,
  effect20name VARCHAR(45) DEFAULT NULL,
  effect20value INT(11) DEFAULT 0,
  effect21valuep INT(11) DEFAULT 0,
  effect21name VARCHAR(45) DEFAULT NULL,
  effect21value INT(11) DEFAULT 0,
  effect22valuep INT(11) DEFAULT 0,
  effect22name VARCHAR(45) DEFAULT NULL,
  effect22value INT(11) DEFAULT 0,
  effect23valuep INT(11) DEFAULT 0,
  effect23name VARCHAR(45) DEFAULT NULL,
  effect23value INT(11) DEFAULT 0,
  effect24valuep INT(11) DEFAULT 0,
  effect24name VARCHAR(45) DEFAULT NULL,
  effect24value INT(11) DEFAULT 0,
  effect25valuep INT(11) DEFAULT 0,
  effect25name VARCHAR(45) DEFAULT NULL,
  effect25value INT(11) DEFAULT 0,
  effect26valuep INT(11) DEFAULT 0,
  effect26name VARCHAR(45) DEFAULT NULL,
  effect26value INT(11) DEFAULT 0,
  effect27valuep INT(11) DEFAULT 0,
  effect27name VARCHAR(45) DEFAULT NULL,
  effect27value INT(11) DEFAULT 0,
  effect28valuep INT(11) DEFAULT 0,
  effect28name VARCHAR(45) DEFAULT NULL,
  effect28value INT(11) DEFAULT 0,
  effect29valuep INT(11) DEFAULT 0,
  effect29name VARCHAR(45) DEFAULT NULL,
  effect29value INT(11) DEFAULT 0,
  effect30valuep INT(11) DEFAULT 0,
  effect30name VARCHAR(45) DEFAULT NULL,
  effect30value INT(11) DEFAULT 0,
  effect31valuep INT(11) DEFAULT 0,
  effect31name VARCHAR(45) DEFAULT NULL,
  effect31value INT(11) DEFAULT 0,
  effect32valuep INT(11) DEFAULT 0,
  effect32name VARCHAR(45) DEFAULT NULL,
  effect32value INT(11) DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
ROW_FORMAT = COMPACT;

--
-- Create table `item_set_items`
--
CREATE TABLE item_set_items (
  id INT(11) NOT NULL AUTO_INCREMENT,
  set_id INT(11) NOT NULL,
  template_id INT(11) NOT NULL,
  isactive TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `item_quality`
--
CREATE TABLE item_quality (
  id INT(11) NOT NULL,
  name VARCHAR(20) NOT NULL,
  cost INT(11) NOT NULL,
  chance INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `item_enchant_profile`
--
CREATE TABLE item_enchant_profile (
  id INT(11) NOT NULL,
  Name VARCHAR(64) NOT NULL,
  level INT(11) NOT NULL,
  percentage TINYINT(1) NOT NULL,
  all_stats TINYINT(1) NOT NULL,
  add_not_exist TINYINT(1) NOT NULL,
  stat_value INT(11) NOT NULL,
  chance FLOAT NOT NULL,
  lower_by TINYINT(4) DEFAULT NULL,
  lower_to SMALLINT(6) DEFAULT NULL,
  cost INT(11) NOT NULL,
  currency INT(11) NOT NULL,
  damage INT(11) NOT NULL,
  damagep INT(11) NOT NULL,
  effect1valuep INT(11) DEFAULT 0,
  effect1name VARCHAR(45) DEFAULT NULL,
  effect1value INT(11) DEFAULT 0,
  effect2valuep INT(11) DEFAULT 0,
  effect2name VARCHAR(45) DEFAULT NULL,
  effect2value INT(11) DEFAULT 0,
  effect3valuep INT(11) DEFAULT 0,
  effect3name VARCHAR(45) DEFAULT NULL,
  effect3value INT(11) DEFAULT 0,
  effect4valuep INT(11) DEFAULT 0,
  effect4name VARCHAR(45) DEFAULT NULL,
  effect4value INT(11) DEFAULT 0,
  effect5valuep INT(11) DEFAULT 0,
  effect5name VARCHAR(45) DEFAULT NULL,
  effect5value INT(11) DEFAULT 0,
  effect6valuep INT(11) DEFAULT 0,
  effect6name VARCHAR(45) DEFAULT NULL,
  effect6value INT(11) DEFAULT 0,
  effect7valuep INT(11) DEFAULT 0,
  effect7name VARCHAR(45) DEFAULT NULL,
  effect7value INT(11) DEFAULT 0,
  effect8valuep INT(11) DEFAULT 0,
  effect8name VARCHAR(45) DEFAULT NULL,
  effect8value INT(11) DEFAULT 0,
  effect9valuep INT(11) DEFAULT 0,
  effect9name VARCHAR(45) DEFAULT NULL,
  effect9value INT(11) DEFAULT 0,
  effect10valuep INT(11) DEFAULT 0,
  effect10name VARCHAR(45) DEFAULT NULL,
  effect10value INT(11) DEFAULT 0,
  effect11valuep INT(11) DEFAULT 0,
  effect11name VARCHAR(45) DEFAULT NULL,
  effect11value INT(11) DEFAULT 0,
  effect12valuep INT(11) DEFAULT 0,
  effect12name VARCHAR(45) DEFAULT NULL,
  effect12value INT(11) DEFAULT 0,
  effect13valuep INT(11) DEFAULT 0,
  effect13name VARCHAR(45) DEFAULT NULL,
  effect13value INT(11) DEFAULT 0,
  effect14valuep INT(11) DEFAULT 0,
  effect14name VARCHAR(45) DEFAULT NULL,
  effect14value INT(11) DEFAULT 0,
  effect15valuep INT(11) DEFAULT 0,
  effect15name VARCHAR(45) DEFAULT NULL,
  effect15value INT(11) DEFAULT 0,
  effect16valuep INT(11) DEFAULT 0,
  effect16name VARCHAR(45) DEFAULT NULL,
  effect16value INT(11) DEFAULT 0,
  effect17valuep INT(11) DEFAULT 0,
  effect17name VARCHAR(45) DEFAULT NULL,
  effect17value INT(11) DEFAULT 0,
  effect18valuep INT(11) DEFAULT 0,
  effect18name VARCHAR(45) DEFAULT NULL,
  effect18value INT(11) DEFAULT 0,
  effect19valuep INT(11) DEFAULT 0,
  effect19name VARCHAR(45) DEFAULT NULL,
  effect19value INT(11) DEFAULT 0,
  effect20valuep INT(11) DEFAULT 0,
  effect20name VARCHAR(45) DEFAULT NULL,
  effect20value INT(11) DEFAULT 0,
  effect21valuep INT(11) DEFAULT 0,
  effect21name VARCHAR(45) DEFAULT NULL,
  effect21value INT(11) DEFAULT 0,
  effect22valuep INT(11) DEFAULT 0,
  effect22name VARCHAR(45) DEFAULT NULL,
  effect22value INT(11) DEFAULT 0,
  effect23valuep INT(11) DEFAULT 0,
  effect23name VARCHAR(45) DEFAULT NULL,
  effect23value INT(11) DEFAULT 0,
  effect24valuep INT(11) DEFAULT 0,
  effect24name VARCHAR(45) DEFAULT NULL,
  effect24value INT(11) DEFAULT 0,
  effect25valuep INT(11) DEFAULT 0,
  effect25name VARCHAR(45) DEFAULT NULL,
  effect25value INT(11) DEFAULT 0,
  effect26valuep INT(11) DEFAULT 0,
  effect26name VARCHAR(45) DEFAULT NULL,
  effect26value INT(11) DEFAULT 0,
  effect27valuep INT(11) DEFAULT 0,
  effect27name VARCHAR(45) DEFAULT NULL,
  effect27value INT(11) DEFAULT 0,
  effect28valuep INT(11) DEFAULT 0,
  effect28name VARCHAR(45) DEFAULT NULL,
  effect28value INT(11) DEFAULT 0,
  effect29valuep INT(11) DEFAULT 0,
  effect29name VARCHAR(45) DEFAULT NULL,
  effect29value INT(11) DEFAULT 0,
  effect30valuep INT(11) DEFAULT 0,
  effect30name VARCHAR(45) DEFAULT NULL,
  effect30value INT(11) DEFAULT 0,
  effect31valuep INT(11) DEFAULT 0,
  effect31name VARCHAR(45) DEFAULT NULL,
  effect31value INT(11) DEFAULT 0,
  effect32valuep INT(11) DEFAULT 0,
  effect32name VARCHAR(45) DEFAULT NULL,
  effect32value INT(11) DEFAULT 0,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (id, level)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
ROW_FORMAT = COMPACT;

--
-- Create column `crafting_xp` on table `crafting_recipes`
--
ALTER TABLE crafting_recipes 
  ADD COLUMN crafting_xp INT(11) NOT NULL;

--
-- Change columns order on table `crafting_recipes`
--
ALTER TABLE crafting_recipes 
 MODIFY crafting_xp INT(11) NOT NULL AFTER allowEssences;

--
-- Create column `aoeAngle` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN aoeAngle FLOAT NOT NULL DEFAULT 360;

--
-- Create column `castingInRun` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN castingInRun TINYINT(1) NOT NULL DEFAULT 0;

--
-- Change columns order on table `abilities`
--
ALTER TABLE abilities 
 MODIFY aoeAngle FLOAT NOT NULL DEFAULT 360 AFTER aoeRadius;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;