-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.06.2021 00:14:52
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `admin`;

--
-- Alter column `createtime` on table `player_shop`
--
ALTER TABLE player_shop 
  CHANGE COLUMN createtime createtime BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create table `claim_upgrade`
--
CREATE TABLE claim_upgrade (
  id INT(11) NOT NULL AUTO_INCREMENT,
  claimID INT(11) NOT NULL,
  locX FLOAT NOT NULL,
  locY FLOAT NOT NULL,
  locZ FLOAT NOT NULL,
  sizeX INT(11) DEFAULT 30,
  sizeZ INT(11) DEFAULT 30,
  sizeY INT(11) DEFAULT 30,
  cost BIGINT(20) DEFAULT 0,
  currency INT(11) DEFAULT 1,
  purchaseItemReq VARCHAR(45) DEFAULT '',
  object_limit_profile INT(11) NOT NULL,
  taxCurrency INT(11) NOT NULL,
  taxAmount BIGINT(20) NOT NULL,
  taxInterval BIGINT(20) NOT NULL,
  taxPeriodPay BIGINT(20) NOT NULL,
  taxPeriodSell BIGINT(20) NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create column `parents` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN parents VARCHAR(256) NOT NULL DEFAULT '';

--
-- Create column `start_build_time` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN start_build_time BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `progress` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN progress INT(11) NOT NULL DEFAULT 0;

--
-- Create column `taskCurrentTime` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN taskCurrentTime BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `taskLastTimeUpdate` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN taskLastTimeUpdate BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `ownerStat` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN ownerStat INT(11) NOT NULL DEFAULT 0;

--
-- Create column `taskPlayerOid` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN taskPlayerOid BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `finalStage` on table `claim_object`
--
ALTER TABLE claim_object 
  ADD COLUMN finalStage TINYINT(1) NOT NULL DEFAULT 0;

--
-- Change columns order on table `claim_object`
--
ALTER TABLE claim_object 
 MODIFY parents VARCHAR(256) NOT NULL DEFAULT '' AFTER parent;
ALTER TABLE claim_object 
 MODIFY isactive TINYINT(1) DEFAULT 1 AFTER finalStage;
ALTER TABLE claim_object 
 MODIFY creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER isactive;
ALTER TABLE claim_object 
 MODIFY updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00' AFTER creationtimestamp;

--
-- Create column `sizeY` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN sizeY INT(11) DEFAULT 30;

--
-- Create column `upgrade` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN `upgrade` INT(11) NOT NULL DEFAULT 0;

--
-- Create column `object_limit_profile` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN object_limit_profile INT(11) NOT NULL DEFAULT -1;

--
-- Create column `taxCurrency` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN taxCurrency INT(11) NOT NULL DEFAULT -1;

--
-- Create column `taxAmount` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN taxAmount BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `taxInterval` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN taxInterval BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `taxPeriodPay` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN taxPeriodPay BIGINT(20) NOT NULL DEFAULT 0;

--
-- Create column `taxPeriodSell` on table `claim`
--
ALTER TABLE claim 
  ADD COLUMN taxPeriodSell BIGINT(20) NOT NULL DEFAULT 0;

--
-- Change columns order on table `claim`
--
ALTER TABLE claim 
 MODIFY sizeY INT(11) DEFAULT 30 AFTER sizeZ;
ALTER TABLE claim 
 MODIFY `upgrade` INT(11) NOT NULL DEFAULT 0 AFTER priority;
ALTER TABLE claim 
 MODIFY isactive TINYINT(1) DEFAULT 1 AFTER taxPeriodSell;
ALTER TABLE claim 
 MODIFY creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER isactive;
ALTER TABLE claim 
 MODIFY updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00' AFTER creationtimestamp;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;