-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.06.2021 00:22:22
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `master`;

--
-- Create column `server_ip` on table `world`
--
ALTER TABLE world 
  ADD COLUMN server_ip VARCHAR(200) DEFAULT NULL;

--
-- Change columns order on table `world`
--
ALTER TABLE world 
 MODIFY server_ip VARCHAR(200) DEFAULT NULL AFTER server_name;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;