--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20.12.2023 22:33:47
-- Source server version: 8.0.35
-- Target server version: 8.0.35
--

SET NAMES 'utf8';

USE admin;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Deleting data from table `server_version`
--
DELETE FROM server_version WHERE server_version = '10.8.0';

--
-- Inserting data into table `server_version`
--
INSERT INTO server_version(server_version, installation_type) VALUES
('10.9.0', 'Core');

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
