-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13.04.2019 20:58:02
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `world_content`;

--
-- Create column `type` on table `skill_profile`
--
ALTER TABLE skill_profile 
  ADD COLUMN type INT(1) NOT NULL;

--
-- Change columns order on table `skill_profile`
--
ALTER TABLE skill_profile 
 MODIFY type INT(1) NOT NULL AFTER id;

--
-- Create column `type` on table `skills`
--
ALTER TABLE skills 
  ADD COLUMN type INT(1) NOT NULL DEFAULT 1;

--
-- Change columns order on table `skills`
--
ALTER TABLE skills 
 MODIFY type INT(1) NOT NULL DEFAULT 1 AFTER skill_profile_id;

--
-- Alter column `coordEffect` on table `resource_node_template`
--
ALTER TABLE resource_node_template 
  CHANGE COLUMN coordEffect coordEffect VARCHAR(64) DEFAULT NULL;

--
-- Create column `skillExp` on table `resource_node_template`
--
ALTER TABLE resource_node_template 
  ADD COLUMN skillExp INT(11) NOT NULL DEFAULT 0;

--
-- Change columns order on table `resource_node_template`
--
ALTER TABLE resource_node_template 
 MODIFY skillExp INT(11) NOT NULL DEFAULT 0 AFTER skillLevelMax;

--
-- Create column `item5` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item5 INT(11) DEFAULT NULL;

--
-- Create column `item5count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item5count INT(11) DEFAULT NULL;

--
-- Create column `item6` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item6 INT(11) DEFAULT NULL;

--
-- Create column `item6count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item6count INT(11) DEFAULT NULL;

--
-- Create column `item7` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item7 INT(11) DEFAULT NULL;

--
-- Create column `item7count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item7count INT(11) DEFAULT NULL;

--
-- Create column `item8` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item8 INT(11) DEFAULT NULL;

--
-- Create column `item8count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN item8count INT(11) DEFAULT NULL;

--
-- Create column `chooseitem5` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem5 INT(11) DEFAULT NULL;

--
-- Create column `chooseitem5count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem5count INT(11) DEFAULT NULL;

--
-- Create column `chooseitem6` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem6 INT(11) DEFAULT NULL;

--
-- Create column `chooseitem6count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem6count INT(11) DEFAULT NULL;

--
-- Create column `chooseitem7` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem7 INT(11) DEFAULT NULL;

--
-- Create column `chooseitem7count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem7count INT(11) DEFAULT NULL;

--
-- Create column `chooseitem8` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem8 INT(11) DEFAULT NULL;

--
-- Create column `chooseitem8count` on table `quests`
--
ALTER TABLE quests 
  ADD COLUMN chooseitem8count INT(11) DEFAULT NULL;

--
-- Change columns order on table `quests`
--
ALTER TABLE quests 
 MODIFY item5 INT(11) DEFAULT NULL AFTER item4count;
ALTER TABLE quests 
 MODIFY item5count INT(11) DEFAULT NULL AFTER item5;
ALTER TABLE quests 
 MODIFY item6 INT(11) DEFAULT NULL AFTER item5count;
ALTER TABLE quests 
 MODIFY item6count INT(11) DEFAULT NULL AFTER item6;
ALTER TABLE quests 
 MODIFY item7 INT(11) DEFAULT NULL AFTER item6count;
ALTER TABLE quests 
 MODIFY item7count INT(11) DEFAULT NULL AFTER item7;
ALTER TABLE quests 
 MODIFY item8 INT(11) DEFAULT NULL AFTER item7count;
ALTER TABLE quests 
 MODIFY item8count INT(11) DEFAULT NULL AFTER item8;
ALTER TABLE quests 
 MODIFY chooseitem5 INT(11) DEFAULT NULL AFTER chooseItem4count;
ALTER TABLE quests 
 MODIFY chooseitem5count INT(11) DEFAULT NULL AFTER chooseitem5;
ALTER TABLE quests 
 MODIFY chooseitem6 INT(11) DEFAULT NULL AFTER chooseitem5count;
ALTER TABLE quests 
 MODIFY chooseitem6count INT(11) DEFAULT NULL AFTER chooseitem6;
ALTER TABLE quests 
 MODIFY chooseitem7 INT(11) DEFAULT NULL AFTER chooseitem6count;
ALTER TABLE quests 
 MODIFY chooseitem7count INT(11) DEFAULT NULL AFTER chooseitem7;
ALTER TABLE quests 
 MODIFY chooseitem8 INT(11) DEFAULT NULL AFTER chooseitem7count;
ALTER TABLE quests 
 MODIFY chooseitem8count INT(11) DEFAULT NULL AFTER chooseitem8;

--
-- Create column `displayName` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN displayName VARCHAR(200) NOT NULL DEFAULT '';

--
-- Create column `exp` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN exp INT(11) NOT NULL DEFAULT 0;

--
-- Create column `addExplev` on table `mob_templates`
--
ALTER TABLE mob_templates 
  ADD COLUMN addExplev INT(11) NOT NULL DEFAULT 0;

--
-- Change columns order on table `mob_templates`
--
ALTER TABLE mob_templates 
 MODIFY displayName VARCHAR(200) NOT NULL DEFAULT '' AFTER name;
ALTER TABLE mob_templates 
 MODIFY exp INT(11) NOT NULL DEFAULT 0 AFTER abilityStatPercent2;
ALTER TABLE mob_templates 
 MODIFY addExplev INT(11) NOT NULL DEFAULT 0 AFTER exp;

--
-- Create column `skillExp` on table `item_templates`
--
ALTER TABLE item_templates 
  ADD COLUMN skillExp INT(11) NOT NULL DEFAULT 0;

--
-- Create column `option4text` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option4text VARCHAR(256) DEFAULT NULL;

--
-- Create column `option4action` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option4action VARCHAR(45) DEFAULT NULL;

--
-- Create column `option4actionID` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option4actionID INT(11) DEFAULT NULL;

--
-- Create column `option4itemReq` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option4itemReq INT(11) DEFAULT -1;

--
-- Create column `option5text` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option5text VARCHAR(256) DEFAULT NULL;

--
-- Create column `option5action` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option5action VARCHAR(45) DEFAULT NULL;

--
-- Create column `option5actionID` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option5actionID INT(11) DEFAULT NULL;

--
-- Create column `option5itemReq` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option5itemReq INT(11) DEFAULT -1;

--
-- Create column `option6text` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option6text VARCHAR(256) DEFAULT NULL;

--
-- Create column `option6action` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option6action VARCHAR(45) DEFAULT NULL;

--
-- Create column `option6actionID` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option6actionID INT(11) DEFAULT NULL;

--
-- Create column `option6itemReq` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option6itemReq INT(11) DEFAULT -1;

--
-- Create column `option7text` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option7text VARCHAR(256) DEFAULT NULL;

--
-- Create column `option7action` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option7action VARCHAR(45) DEFAULT NULL;

--
-- Create column `option7actionID` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option7actionID INT(11) DEFAULT NULL;

--
-- Create column `option7itemReq` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option7itemReq INT(11) DEFAULT -1;

--
-- Create column `option8text` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option8text VARCHAR(256) DEFAULT NULL;

--
-- Create column `option8action` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option8action VARCHAR(45) DEFAULT NULL;

--
-- Create column `option8actionID` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option8actionID INT(11) DEFAULT NULL;

--
-- Create column `option8itemReq` on table `dialogue`
--
ALTER TABLE dialogue 
  ADD COLUMN option8itemReq INT(11) DEFAULT -1;

--
-- Change columns order on table `dialogue`
--
ALTER TABLE dialogue 
 MODIFY isactive TINYINT(1) DEFAULT 1 AFTER option8itemReq;
ALTER TABLE dialogue 
 MODIFY creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER isactive;
ALTER TABLE dialogue 
 MODIFY updatetimestamp DATETIME DEFAULT '2000-01-01 00:00:00' AFTER creationtimestamp;

--
-- Alter column `id` on table `currencies`
--
ALTER TABLE currencies 
  MODIFY id BIGINT(20) NOT NULL;

--
-- Drop index `PRIMARY` from table `currencies`
--
ALTER TABLE currencies 
   DROP PRIMARY KEY;

--
-- Alter column `id` on table `currencies`
--
ALTER TABLE currencies 
  CHANGE COLUMN id id INT(11) NOT NULL;

--
-- Alter column `id` on table `currencies`
--
ALTER TABLE currencies 
  MODIFY id INT(11) NOT NULL AUTO_INCREMENT,
  ADD PRIMARY KEY (id);

--
-- Alter column `activationEffect1` on table `abilities`
--
ALTER TABLE abilities 
  CHANGE COLUMN activationEffect1 activationEffect1 INT(11) DEFAULT NULL;

--
-- Create column `activationEffect4` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN activationEffect4 INT(11) DEFAULT 0;

--
-- Create column `activationTarget4` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN activationTarget4 VARCHAR(32) DEFAULT '0';

--
-- Create column `activationEffect5` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN activationEffect5 INT(11) DEFAULT 0;

--
-- Create column `activationTarget5` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN activationTarget5 VARCHAR(32) DEFAULT '0';

--
-- Create column `activationEffect6` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN activationEffect6 INT(11) DEFAULT 0;

--
-- Create column `activationTarget6` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN activationTarget6 VARCHAR(32) DEFAULT '0';

--
-- Create column `coordEffect3event` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN coordEffect3event VARCHAR(32) DEFAULT NULL;

--
-- Create column `coordEffect3` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN coordEffect3 VARCHAR(64) DEFAULT NULL;

--
-- Create column `exp` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN exp INT(11) NOT NULL DEFAULT 0;

--
-- Create column `consumeOnActivation` on table `abilities`
--
ALTER TABLE abilities 
  ADD COLUMN consumeOnActivation TINYINT(1) NOT NULL DEFAULT 0;

--
-- Change columns order on table `abilities`
--
ALTER TABLE abilities 
 MODIFY activationEffect4 INT(11) DEFAULT 0 AFTER activationTarget3;
ALTER TABLE abilities 
 MODIFY activationTarget4 VARCHAR(32) DEFAULT '0' AFTER activationEffect4;
ALTER TABLE abilities 
 MODIFY activationEffect5 INT(11) DEFAULT 0 AFTER activationTarget4;
ALTER TABLE abilities 
 MODIFY activationTarget5 VARCHAR(32) DEFAULT '0' AFTER activationEffect5;
ALTER TABLE abilities 
 MODIFY activationEffect6 INT(11) DEFAULT 0 AFTER activationTarget5;
ALTER TABLE abilities 
 MODIFY activationTarget6 VARCHAR(32) DEFAULT '0' AFTER activationEffect6;
ALTER TABLE abilities 
 MODIFY coordEffect3event VARCHAR(32) DEFAULT NULL AFTER coordEffect2;
ALTER TABLE abilities 
 MODIFY coordEffect3 VARCHAR(64) DEFAULT NULL AFTER coordEffect3event;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;