--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13.04.2019 21:35:50
--



SET NAMES 'utf8';
USE `world_content`;

--
-- Disabling DML triggers for game_setting
--
DROP TRIGGER IF EXISTS game_setting_trigger;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Updating data of table game_setting
--
UPDATE game_setting SET value = '0.25', updatetimestamp = '2019-04-13 17:00:55' WHERE id = 12;

--
-- Inserting data into table game_setting
--
INSERT INTO game_setting(id, name, datatype, value, isactive, creationtimestamp, updatetimestamp) VALUES
(NULL, 'HIT_CHANCE_PERCENTAGE_CAP', 'int', '30', 1, '2019-04-13 16:56:30', '2000-01-01 00:00:00'),
(NULL, 'PARRY_PERCENTAGE_CAP', 'int', '40', 1, '2019-04-13 16:56:57', '2000-01-01 00:00:00'),
(NULL, 'RESOURCE_HARVEST_XP_REWARD', 'int', '100', 1, '2019-04-13 16:59:37', '2000-01-01 00:00:00'),
(NULL, 'UPGRADE_CLAIM_OBJECT_ITEMS_FROM_INVENTORY', 'bool', 'false', 1, '2019-04-13 17:01:13', '2000-01-01 00:00:00');
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

--
-- Enabling DML triggers for 
--
DELIMITER ;;

--
-- Enabling DML triggers for game_setting
--
CREATE 
TRIGGER game_setting_trigger
	BEFORE UPDATE
	ON game_setting
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Enabling DML triggers for 
--
DELIMITER ;