-- 
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26.11.2019 11:19:05
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `admin`;

--
-- Alter column `mailId` on table `history_character_mail`
--
ALTER TABLE history_character_mail 
  MODIFY mailId INT(11) NOT NULL;

--
-- Drop index `PRIMARY` from table `history_character_mail`
--
ALTER TABLE history_character_mail 
   DROP PRIMARY KEY;

--
-- Create column `id` on table `history_character_mail`
--
ALTER TABLE history_character_mail 
  ADD COLUMN id INT(11) NOT NULL;

--
-- Change columns order on table `history_character_mail`
--
ALTER TABLE history_character_mail 
 MODIFY id INT(11) NOT NULL FIRST;

--
-- Alter column `id` on table `history_character_mail`
--
ALTER TABLE history_character_mail 
  MODIFY id INT(11) NOT NULL AUTO_INCREMENT,
  ADD PRIMARY KEY (id);

--
-- Create table `ranking_run`
--
CREATE TABLE ranking_run (
  world VARCHAR(50) NOT NULL,
  last_run BIGINT(20) NOT NULL,
  PRIMARY KEY (world)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `rankings`
--
CREATE TABLE rankings (
  id INT(11) NOT NULL AUTO_INCREMENT,
  pos INT(11) NOT NULL,
  player BIGINT(200) NOT NULL,
  ranking INT(11) NOT NULL,
  value INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `achivement_data`
--
CREATE TABLE achivement_data (
  id INT(11) NOT NULL AUTO_INCREMENT,
  playerOid BIGINT(20) NOT NULL,
  type INT(11) NOT NULL,
  obj VARCHAR(200) NOT NULL,
  rankingId INT(11) NOT NULL,
  achievementId INT(11) NOT NULL,
  acquired TINYINT(1) NOT NULL,
  value INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;