-- 
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2018-03-25 16:43:03
-- Please backup your target database before running this script
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE `admin`;


CREATE TABLE `server` (
  `action` varchar(10) DEFAULT NULL,
  `status` tinyint(1) DEFAULT '0'
) ENGINE=MEMORY DEFAULT CHARSET=utf8;


CREATE TABLE `server_status` (
  `server` varchar(10) DEFAULT NULL,
  `status` tinyint(1) DEFAULT '0'
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

insert into server_status values("auth",0),("world",0);

--
-- Alter table "account"
--
ALTER TABLE account
  CHANGE COLUMN last_logout last_logout TIMESTAMP NOT NULL DEFAULT '2014-01-01 00:00:00';

--
-- Alter table "claim"
--
ALTER TABLE claim
  ADD COLUMN instanceOwner BIGINT(20) NOT NULL DEFAULT 0 AFTER instance,
  ADD COLUMN instanceGuild BIGINT(20) NOT NULL DEFAULT -1 AFTER instanceOwner,
  CHANGE COLUMN purchaseItemReq purchaseItemReq VARCHAR(45) DEFAULT '' AFTER currency,
  CHANGE COLUMN creationtimestamp creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER isactive;

--
-- Alter table "claim_action"
--
ALTER TABLE claim_action
  CHANGE COLUMN creationtimestamp creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

--
-- Alter table "claim_object"
--
ALTER TABLE claim_object
  CHANGE COLUMN creationtimestamp creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

--
-- Alter table "claim_permission"
--
ALTER TABLE claim_permission
  CHANGE COLUMN creationtimestamp creationtimestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

--
-- Create table "cooldowns"
--
CREATE TABLE cooldowns (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cid VARCHAR(100) NOT NULL,
  duration INT(11) NOT NULL,
  startTime BIGINT(16) NOT NULL,
  obj_oid INT(13) NOT NULL,
  PRIMARY KEY (id),
  INDEX obj_oid (obj_oid)
)
ENGINE = INNODB
AUTO_INCREMENT = 52887
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "world_time"
--
CREATE TABLE world_time (
  id INT(11) NOT NULL AUTO_INCREMENT,
  world_name VARCHAR(50) NOT NULL,
  year INT(11) NOT NULL DEFAULT 1,
  month INT(11) NOT NULL DEFAULT 1,
  day INT(11) NOT NULL DEFAULT 1,
  hour INT(11) NOT NULL DEFAULT 0,
  minute INT(11) NOT NULL DEFAULT 0,
  second INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  INDEX world_name (world_name),
  UNIQUE INDEX world_name_2 (world_name)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

DELIMITER ;;

--
-- Create trigger "claim_action_trigger"
--
CREATE TRIGGER claim_action_trigger
	BEFORE UPDATE
	ON claim_action
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Create trigger "claim_object_trigger"
--
CREATE TRIGGER claim_object_trigger
	BEFORE UPDATE
	ON claim_object
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Create trigger "claim_permission_trigger"
--
CREATE TRIGGER claim_permission_trigger
	BEFORE UPDATE
	ON claim_permission
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

--
-- Create trigger "claim_trigger"
--
CREATE TRIGGER claim_trigger
	BEFORE UPDATE
	ON claim
	FOR EACH ROW
SET NEW.updatetimestamp = CURRENT_TIMESTAMP
;;

DELIMITER ;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
