-- 
-- Script was generated by Devart dbForge Schema Compare for MySQL, Version 4.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/schemacompare
-- Script date 2017-12-29 21:39:32
-- Server version: 5.7.20
-- Please backup your target database before running this script
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

USE `atavism`;


--
-- Alter table "backdating_tables"
--
ALTER TABLE backdating_tables
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "custom_banned"
--
ALTER TABLE custom_banned
  CHANGE COLUMN name name VARCHAR(20) NOT NULL,
  CHANGE COLUMN reason reason VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN bannedby bannedby VARCHAR(20) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "custom_profanity"
--
ALTER TABLE custom_profanity
  CHANGE COLUMN name name VARCHAR(20) NOT NULL,
  CHANGE COLUMN reason reason VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN bannedby bannedby VARCHAR(20) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Create table "history_objstore"
--
CREATE TABLE history_objstore (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  obj_id BIGINT(20) DEFAULT NULL,
  namespace_int TINYINT(4) DEFAULT NULL,
  world_name VARCHAR(64) DEFAULT NULL,
  locX INT(11) DEFAULT NULL,
  locY INT(11) DEFAULT NULL,
  locZ INT(11) DEFAULT NULL,
  instance BIGINT(20) DEFAULT NULL,
  metadata VARCHAR(255) DEFAULT NULL,
  type VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  persistence_key VARCHAR(255) DEFAULT NULL,
  data LONGBLOB DEFAULT NULL,
  timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id),
  INDEX metadata (metadata),
  INDEX name (name),
  INDEX persistence_key (persistence_key),
  INDEX type (type)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Alter table "namespaces"
--
ALTER TABLE namespaces
  CHANGE COLUMN namespace_string namespace_string VARCHAR(64) NOT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "objstore"
--
ALTER TABLE objstore
  CHANGE COLUMN world_name world_name VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN metadata metadata VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN type type VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN name name VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN persistence_key persistence_key VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "oid_manager"
--
ALTER TABLE oid_manager
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "plugin_status"
--
ALTER TABLE plugin_status
  CHANGE COLUMN world_name world_name VARCHAR(64) NOT NULL,
  CHANGE COLUMN agent_name agent_name VARCHAR(64) NOT NULL,
  CHANGE COLUMN plugin_name plugin_name VARCHAR(64) NOT NULL,
  CHANGE COLUMN plugin_type plugin_type VARCHAR(16) NOT NULL,
  CHANGE COLUMN host_name host_name VARCHAR(64) NOT NULL,
  CHANGE COLUMN status status VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN info info VARCHAR(255) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

ALTER TABLE plugin_status
  DROP INDEX agent_name,
  ADD INDEX agent_name USING BTREE (agent_name);

ALTER TABLE plugin_status
  DROP INDEX world_name,
  ADD INDEX world_name USING BTREE (world_name);

--
-- Alter table "player_character"
--
ALTER TABLE player_character
  CHANGE COLUMN world_name world_name VARCHAR(64) NOT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

DELIMITER ;;

--
-- Create trigger "history_objstore_trigger"
--
CREATE TRIGGER history_objstore_trigger
	BEFORE UPDATE
	ON objstore
	FOR EACH ROW
BEGIN
		IF OLD.data != NEW.data
        THEN
		INSERT INTO history_objstore
        (
             obj_id,
			 namespace_int,
			 world_name,
			 locX,
			 locY,
			 locZ,
			 instance,
			 metadata,
			 type,
			 name,
			 persistence_key,
			 data
		)
		VALUES
		(
             NEW.obj_id,
			 NEW.namespace_int,
			 NEW.world_name,
			 NEW.locX,
			 NEW.locY,
			 NEW.locZ,
			 NEW.instance,
			 NEW.metadata,
			 NEW.type,
			 NEW.name,
			 NEW.persistence_key,
			 NEW.data
		);
        END IF;
END
;;

DELIMITER ;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;