--
-- Script was generated by Devart dbForge Data Compare for MySQL, Version 5.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/datacompare
-- Script date 2017-12-29 21:56:29
-- Please backup your target database before running this script
--



SET NAMES 'utf8';
USE `master`;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Inserting data into table world
--
INSERT INTO world(world_id, dev_id, world_name, pretty_name, description, server_name, server_port, public, approved, patcher_URL, media_URL, logo_URL, detail_URL, display_order, population, max_population, server_type, status, last_update) VALUES
(3, -1, 'Local', NULL, NULL, 'localhost', 5040, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 100, NULL, 'Online', '2017-12-12 17:21:38');
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;