-- 
-- Script was generated by Devart dbForge Schema Compare for MySQL, Version 4.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/schemacompare
-- Script date 2017-12-29 21:41:02
-- Server version: 5.7.20
-- Please backup your target database before running this script
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

USE `world_content`;


--
-- Drop table "claim_permission"
--
DROP TABLE claim_permission;

--
-- Drop table "claim_object"
--
DROP TABLE claim_object;

--
-- Drop table "claim_action"
--
DROP TABLE claim_action;

--
-- Drop table "claim"
--
DROP TABLE claim;

--
-- Alter table "abilities"
--
ALTER TABLE abilities
  ADD COLUMN reagentCount INT(11) DEFAULT 1 AFTER reagentRequired,
  ADD COLUMN reagent2Required INT(11) DEFAULT -1 AFTER reagentConsumed,
  ADD COLUMN reagent2Count INT(11) DEFAULT 1 AFTER reagent2Required,
  ADD COLUMN reagent2Consumed TINYINT(1) DEFAULT 1 AFTER reagent2Count,
  ADD COLUMN reagent3Required INT(11) DEFAULT -1 AFTER reagent2Consumed,
  ADD COLUMN reagent3Count INT(11) DEFAULT 1 AFTER reagent3Required,
  ADD COLUMN reagent3Consumed TINYINT(1) DEFAULT 1 AFTER reagent3Count,
  ADD COLUMN aoeType VARCHAR(45) DEFAULT NULL AFTER aoeRadius,
  ADD COLUMN reqFacingTarget TINYINT(1) DEFAULT 0 AFTER reqTarget,
  ADD COLUMN autoRotateToTarget TINYINT(1) DEFAULT 0 AFTER reqFacingTarget,
  ADD COLUMN relativePositionReq INT(1) DEFAULT 0 AFTER autoRotateToTarget,
  ADD COLUMN startCooldownsOnActivation TINYINT(1) DEFAULT 0 AFTER weaponCooldown,
  ADD COLUMN interceptType INT(11) DEFAULT NULL AFTER tooltip,
  ADD COLUMN chance FLOAT NOT NULL DEFAULT 0 AFTER updatetimestamp,
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "arena_teams"
--
ALTER TABLE arena_teams
  ADD COLUMN spawnX FLOAT DEFAULT NULL AFTER goal,
  ADD COLUMN spawnY FLOAT DEFAULT NULL AFTER spawnX,
  ADD COLUMN spawnZ FLOAT DEFAULT NULL AFTER spawnY;

--
-- Alter table "arena_templates"
--
ALTER TABLE arena_templates
  DROP COLUMN worldFile,
  DROP COLUMN team1Name,
  DROP COLUMN team1Size,
  DROP COLUMN team1Race,
  DROP COLUMN team2Name,
  DROP COLUMN team2Race,
  DROP COLUMN team3Name,
  DROP COLUMN team3Size,
  DROP COLUMN team3Race,
  DROP COLUMN team4Name,
  DROP COLUMN team4Size,
  DROP COLUMN team4Race,
  DROP COLUMN team1Goal,
  DROP COLUMN team2Goal,
  DROP COLUMN team3Goal,
  DROP COLUMN team4Goal,
  DROP COLUMN victoryCondition,
  DROP COLUMN raceOption1,
  DROP COLUMN raceOption2,
  CHANGE COLUMN arenaType arenaType INT(11) DEFAULT 1 AFTER id,
  CHANGE COLUMN name name VARCHAR(64) NOT NULL AFTER arenaType,
  ADD COLUMN arenaCategory INT(11) DEFAULT 1 AFTER name,
  CHANGE COLUMN arenaDifficulty arenaInstanceID INT(11) NOT NULL AFTER arenaCategory,
  CHANGE COLUMN length length INT(11) DEFAULT NULL AFTER arenaInstanceID,
  CHANGE COLUMN team2Size defaultWinner INT(11) DEFAULT NULL AFTER length,
  ADD COLUMN team1 INT(11) NOT NULL DEFAULT -1 AFTER defaultWinner,
  ADD COLUMN team2 INT(11) DEFAULT -1 AFTER team1,
  ADD COLUMN team3 INT(11) DEFAULT -1 AFTER team2,
  ADD COLUMN team4 INT(11) DEFAULT -1 AFTER team3,
  ADD COLUMN levelReq INT(11) DEFAULT 1 AFTER team4,
  CHANGE COLUMN numTeams levelMax INT(11) NOT NULL AFTER levelReq,
  CHANGE COLUMN victoryCurrency victoryCurrency INT(11) DEFAULT NULL AFTER levelMax,
  CHANGE COLUMN isactive isactive TINYINT(1) DEFAULT 1 AFTER defeatExp,
  ADD COLUMN start_hour INT(2) NOT NULL DEFAULT 0 AFTER isactive,
  ADD COLUMN start_minute INT(2) NOT NULL DEFAULT 0 AFTER start_hour,
  ADD COLUMN end_hour INT(2) NOT NULL DEFAULT 0 AFTER start_minute,
  ADD COLUMN end_minute INT(2) NOT NULL DEFAULT 0 AFTER end_hour,
  CHANGE COLUMN creationtimestamp creationtimestamp TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00' AFTER end_minute,
  ADD COLUMN description VARCHAR(256) NOT NULL AFTER updatetimestamp;

--
-- Alter table "build_object_template"
--
ALTER TABLE build_object_template
  ADD COLUMN buildTaskReqPlayer TINYINT(1) NOT NULL DEFAULT 1 AFTER distanceReq,
  ADD COLUMN validClaimType INT(11) NOT NULL DEFAULT 0 AFTER buildTaskReqPlayer,
  ADD COLUMN interactionType VARCHAR(45) DEFAULT NULL AFTER availableFromItemOnly,
  ADD COLUMN interactionID INT(11) DEFAULT -1 AFTER interactionType,
  ADD COLUMN interactionData1 VARCHAR(45) DEFAULT NULL AFTER interactionID,
  ADD COLUMN lockable TINYINT(1) DEFAULT 0 AFTER interactionData1,
  ADD COLUMN lockLimit INT(11) DEFAULT 1 AFTER lockable;

--
-- Alter table "character_create_template"
--
ALTER TABLE character_create_template
  ADD COLUMN respawnInstance INT(11) NOT NULL DEFAULT -1 AFTER updatetimestamp,
  ADD COLUMN respawnPosX FLOAT(8, 2) NOT NULL DEFAULT 0.00 AFTER respawnInstance,
  ADD COLUMN respawnPosY FLOAT(8, 2) NOT NULL DEFAULT 0.00 AFTER respawnPosX,
  ADD COLUMN respawnPosZ FLOAT(8, 2) NOT NULL DEFAULT 0.00 AFTER respawnPosY,
  ADD COLUMN startingLevel INT(11) NOT NULL DEFAULT 1 AFTER respawnPosZ;

--
-- Alter table "crafting_recipes"
--
ALTER TABLE crafting_recipes
  CHANGE COLUMN component9count component9count INT(11) DEFAULT 1,
  CHANGE COLUMN component10count component10count INT(11) DEFAULT 1,
  CHANGE COLUMN component11count component11count INT(11) DEFAULT 1,
  CHANGE COLUMN component12count component12count INT(11) DEFAULT 1,
  CHANGE COLUMN component13count component13count INT(11) DEFAULT 1,
  CHANGE COLUMN component14count component14count INT(11) DEFAULT 1,
  CHANGE COLUMN component15count component15count INT(11) DEFAULT 1,
  CHANGE COLUMN component16count component16count INT(11) DEFAULT 1;

--
-- Alter table "currencies"
--
ALTER TABLE currencies
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "dialogue"
--
ALTER TABLE dialogue
  ADD COLUMN option1itemReq INT(11) DEFAULT -1 AFTER option1actionID,
  ADD COLUMN option2itemReq INT(11) DEFAULT -1 AFTER option2actionID,
  ADD COLUMN option3itemReq INT(11) DEFAULT -1 AFTER option3actionID;

--
-- Alter table "effects"
--
ALTER TABLE effects
  ADD COLUMN removeBonusWhenEffectRemoved TINYINT(1) NOT NULL DEFAULT 0 AFTER bonusEffect,
  ADD COLUMN chance FLOAT NOT NULL DEFAULT 0 AFTER updatetimestamp;

--
-- Alter table "faction_stances"
--
ALTER TABLE faction_stances
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "factions"
--
ALTER TABLE factions
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "item_templates"
--
ALTER TABLE item_templates
  CHANGE COLUMN purchaseCost purchaseCost INT(11) DEFAULT 0,
  ADD COLUMN actionBarAllowed TINYINT(1) NOT NULL DEFAULT 0 AFTER updatetimestamp;

--
-- Alter table "item_weights"
--
ALTER TABLE item_weights
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "loot_tables"
--
ALTER TABLE loot_tables
  CHANGE COLUMN item1count item1count INT(11) DEFAULT 0,
  CHANGE COLUMN item1chance item1chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item2count item2count INT(11) DEFAULT 0,
  CHANGE COLUMN item2chance item2chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item3count item3count INT(11) DEFAULT 0,
  CHANGE COLUMN item3chance item3chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item4count item4count INT(11) DEFAULT 0,
  CHANGE COLUMN item4chance item4chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item5count item5count INT(11) DEFAULT 0,
  CHANGE COLUMN item5chance item5chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item6count item6count INT(11) DEFAULT 0,
  CHANGE COLUMN item6chance item6chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item7count item7count INT(11) DEFAULT 0,
  CHANGE COLUMN item7chance item7chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item8count item8count INT(11) DEFAULT 0,
  CHANGE COLUMN item8chance item8chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item9count item9count INT(11) DEFAULT 0,
  CHANGE COLUMN item9chance item9chance FLOAT(10, 7) DEFAULT 0.0000000,
  CHANGE COLUMN item10count item10count INT(11) DEFAULT 0,
  CHANGE COLUMN item10chance item10chance FLOAT(10, 7) DEFAULT 0.0000000;

--
-- Alter table "merchant_item"
--
ALTER TABLE merchant_item
  CHANGE COLUMN count count INT(11) DEFAULT -1,
  CHANGE COLUMN refreshTime refreshTime INT(11) DEFAULT 0;

--
-- Alter table "merchant_tables"
--
ALTER TABLE merchant_tables
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "mob_loot"
--
ALTER TABLE mob_loot
  CHANGE COLUMN dropChance dropChance FLOAT(10, 7) DEFAULT NULL;

--
-- Alter table "mob_templates"
--
ALTER TABLE mob_templates
  ADD COLUMN skinningLootTable INT(11) DEFAULT -1 AFTER subSpecies,
  ADD COLUMN skinningLevelReq INT(11) DEFAULT 0 AFTER skinningLootTable,
  ADD COLUMN attackDistance FLOAT DEFAULT 0 AFTER autoAttack,
  ADD COLUMN ability0 INT(11) DEFAULT -1 AFTER attackDistance,
  ADD COLUMN abilityStatReq0 VARCHAR(45) DEFAULT NULL AFTER ability0,
  ADD COLUMN abilityStatPercent0 INT(11) DEFAULT 0 AFTER abilityStatReq0,
  ADD COLUMN ability1 INT(11) DEFAULT -1 AFTER abilityStatPercent0,
  ADD COLUMN abilityStatReq1 VARCHAR(45) DEFAULT NULL AFTER ability1,
  ADD COLUMN abilityStatPercent1 INT(11) DEFAULT 0 AFTER abilityStatReq1,
  ADD COLUMN ability2 INT(11) DEFAULT -1 AFTER abilityStatPercent1,
  ADD COLUMN abilityStatReq2 VARCHAR(45) DEFAULT NULL AFTER ability2,
  ADD COLUMN abilityStatPercent2 INT(11) DEFAULT 0 AFTER abilityStatReq2;

--
-- Alter table "patrol_path"
--
ALTER TABLE patrol_path
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "quest_objectives"
--
ALTER TABLE quest_objectives
  ADD COLUMN targets VARCHAR(256) NOT NULL AFTER updatetimestamp;

--
-- Create table "ranking1"
--
CREATE TABLE ranking1 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  obj_id INT(11) DEFAULT NULL,
  data INT(11) DEFAULT NULL,
  blobdata BLOB DEFAULT NULL,
  creationtimestamp TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  updatetimestamp DATETIME DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Alter table "skills"
--
ALTER TABLE skills
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Alter table "spawn_data"
--
ALTER TABLE spawn_data
  CHANGE COLUMN locX locX FLOAT(8, 2) DEFAULT NULL,
  CHANGE COLUMN locY locY FLOAT(8, 2) DEFAULT NULL,
  CHANGE COLUMN locZ locZ FLOAT(8, 2) DEFAULT NULL,
  ADD COLUMN spawnActiveStartHour INT(11) DEFAULT -1 AFTER corpseDespawnTime,
  ADD COLUMN spawnActiveEndHour INT(11) DEFAULT -1 AFTER spawnActiveStartHour,
  ADD COLUMN alternateSpawnMobTemplate INT(11) NOT NULL DEFAULT -1 AFTER spawnActiveEndHour,
  ADD COLUMN otherActions VARCHAR(256) NOT NULL AFTER startsDialogues;

--
-- Alter table "users"
--
ALTER TABLE users
ENGINE = INNODB,
  ROW_FORMAT = DYNAMIC;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;