--
-- Script was generated by Devart dbForge Data Compare for MySQL, Version 5.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/datacompare
-- Script date 2017-12-29 21:55:09
-- Please backup your target database before running this script
--



SET NAMES 'utf8';
USE `atavism`;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Inserting data into table namespaces
--
INSERT INTO namespaces(namespace_string, namespace_int) VALUES
('NS.billing', 15),
('NS.classability', 14),
('NS.faction', 17),
('NS.instance', 12),
('NS.trainer', 13),
('NS.wminstance', 11),
('social', 16);

--
-- Updating data of table oid_manager
--
UPDATE oid_manager SET free_oid = 37701 WHERE token = 1;
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;