-- 
-- Script was generated by Devart dbForge Schema Compare for MySQL, Version 4.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/schemacompare
-- Script date 2017-12-29 21:40:01
-- Server version: 5.7.20
-- Please backup your target database before running this script
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

USE `master`;


--
-- Alter table "account"
--
ALTER TABLE account
  CHANGE COLUMN username username VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN password password VARCHAR(128) DEFAULT NULL,
  CHANGE COLUMN email email VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN activation_key activation_key VARCHAR(32) DEFAULT NULL,
  ADD COLUMN coin_current INT(11) NOT NULL DEFAULT 0 AFTER last_modified_at,
  ADD COLUMN coin_total INT(11) NOT NULL DEFAULT 0 AFTER coin_current,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "account_character"
--
ALTER TABLE account_character
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Create table "account_purchases"
--
CREATE TABLE account_purchases (
  id INT(11) NOT NULL AUTO_INCREMENT,
  account_id BIGINT(20) NOT NULL,
  itemID INT(11) DEFAULT NULL,
  itemCount INT(11) DEFAULT NULL,
  itemPurchaseDate TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  itemClaimDate TIMESTAMP NULL DEFAULT NULL,
  itemClaims TEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "account_setting"
--
CREATE TABLE account_setting (
  id INT(11) NOT NULL AUTO_INCREMENT,
  account_id INT(11) NOT NULL,
  setting VARCHAR(45) NOT NULL,
  settingValue VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Alter table "developer"
--
ALTER TABLE developer
  CHANGE COLUMN email email VARCHAR(64) NOT NULL,
  CHANGE COLUMN company company VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN password password VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN size size VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN skill skill VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN prior prior VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN genre genre VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN idea idea TEXT DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

--
-- Alter table "world"
--
ALTER TABLE world
  CHANGE COLUMN world_name world_name VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN pretty_name pretty_name VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN description description TEXT DEFAULT NULL,
  CHANGE COLUMN server_name server_name VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN patcher_URL patcher_URL VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN media_URL media_URL VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN logo_URL logo_URL VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN detail_URL detail_URL VARCHAR(255) DEFAULT NULL,
  CHANGE COLUMN server_type server_type VARCHAR(64) DEFAULT NULL,
  CHANGE COLUMN status status VARCHAR(64) DEFAULT NULL,
  CHARACTER SET utf8,
  COLLATE utf8_general_ci;

DELIMITER ;;

--
-- Create trigger "account_purchases_trigger"
--
CREATE TRIGGER account_purchases_trigger
	BEFORE UPDATE
	ON account_purchases
	FOR EACH ROW
BEGIN
		SET NEW.itemClaimDate = CURRENT_TIMESTAMP;
END
;;

DELIMITER ;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;