--
-- Script was generated by Devart dbForge Data Compare for MySQL, Version 5.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/datacompare
-- Script date 2017-12-29 21:53:11
-- Please backup your target database before running this script
--



SET NAMES 'utf8';
USE `admin`;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Updating data of table instance_template
--
UPDATE instance_template SET globalWaterHeight = -200, lastUpdate = '2016-07-11 05:03:22' WHERE id = 29;
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;