--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2018-03-25 16:54:33
--



SET NAMES 'utf8';
USE `master`;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Deleting data from table world
--
DELETE FROM world WHERE world_id = 3;
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;