-- 
-- Script was generated by Devart dbForge Schema Compare for MySQL, Version 4.1.17.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/schemacompare
-- Script date 2017-12-29 21:38:39
-- Server version: 5.7.20
-- Please backup your target database before running this script
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

USE `admin`;


--
-- Alter table "account"
--
ALTER TABLE account
  CHANGE COLUMN last_logout last_logout TIMESTAMP NOT NULL DEFAULT '2013-12-31 18:00:00';

--
-- Alter table "account_purchases"
--
ALTER TABLE account_purchases
  ADD COLUMN id INT(11) NOT NULL AUTO_INCREMENT FIRST,
  ADD COLUMN used TINYINT(1) DEFAULT 0 AFTER itemClaims,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (id);

--
-- Alter table "character_mail"
--
ALTER TABLE character_mail
  ADD COLUMN isAccountMail TINYINT(1) NOT NULL DEFAULT 0 AFTER mailArchive;

--
-- Create table "claim"
--
CREATE TABLE claim (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL,
  instance INT(11) NOT NULL DEFAULT -1,
  locX FLOAT NOT NULL,
  locY FLOAT NOT NULL,
  locZ FLOAT NOT NULL,
  claimType INT(11) NOT NULL DEFAULT 0,
  owner BIGINT(20) DEFAULT NULL,
  size INT(11) DEFAULT 30,
  sizeZ INT(11) DEFAULT 30,
  forSale TINYINT(1) DEFAULT 0,
  sellerName VARCHAR(45) DEFAULT NULL,
  cost INT(11) DEFAULT 0,
  currency INT(11) DEFAULT 1,
  purchaseItemReq INT(11) DEFAULT -1,
  taxPaidUntil TIMESTAMP NULL DEFAULT NULL,
  claimItemTemplate INT(11) DEFAULT -1,
  bondItemTemplate INT(11) DEFAULT -1,
  bondPaidUntil TIMESTAMP NULL DEFAULT NULL,
  priority INT(11) NOT NULL DEFAULT 1,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  updatetimestamp DATETIME DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "claim_action"
--
CREATE TABLE claim_action (
  id INT(11) NOT NULL AUTO_INCREMENT,
  claimID INT(11) DEFAULT NULL,
  action VARCHAR(45) DEFAULT NULL,
  brushType VARCHAR(45) NOT NULL,
  locX FLOAT NOT NULL,
  locY FLOAT NOT NULL,
  locZ FLOAT NOT NULL,
  material SMALLINT(6) NOT NULL,
  normalX FLOAT NOT NULL,
  normalY FLOAT NOT NULL,
  normalZ FLOAT NOT NULL,
  sizeX FLOAT NOT NULL,
  sizeY FLOAT NOT NULL,
  sizeZ FLOAT NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  updatetimestamp DATETIME DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "claim_object"
--
CREATE TABLE claim_object (
  id INT(11) NOT NULL AUTO_INCREMENT,
  claimID INT(11) DEFAULT NULL,
  template INT(11) DEFAULT NULL,
  stage INT(11) NOT NULL DEFAULT 0,
  complete TINYINT(1) NOT NULL DEFAULT 0,
  parent INT(11) DEFAULT -1,
  gameObject VARCHAR(256) DEFAULT NULL,
  locX FLOAT DEFAULT NULL,
  locY FLOAT DEFAULT NULL,
  locZ FLOAT DEFAULT NULL,
  orientX FLOAT DEFAULT NULL,
  orientY FLOAT DEFAULT NULL,
  orientZ FLOAT DEFAULT NULL,
  orientW FLOAT DEFAULT NULL,
  itemID INT(11) DEFAULT NULL,
  objectState VARCHAR(64) DEFAULT NULL,
  health INT(11) DEFAULT 1,
  maxHealth INT(11) DEFAULT 1,
  item1 INT(11) DEFAULT -1,
  item1Count INT(11) DEFAULT 0,
  item2 INT(11) DEFAULT -1,
  item2Count INT(11) DEFAULT 0,
  item3 INT(11) DEFAULT -1,
  item3Count INT(11) DEFAULT 0,
  item4 INT(11) DEFAULT -1,
  item4Count INT(11) DEFAULT 0,
  item5 INT(11) DEFAULT -1,
  item5Count INT(11) DEFAULT 0,
  item6 INT(11) DEFAULT -1,
  item6Count INT(11) DEFAULT 0,
  lockTemplateID INT(11) DEFAULT -1,
  lockDurability INT(11) DEFAULT 0,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  updatetimestamp DATETIME DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "claim_permission"
--
CREATE TABLE claim_permission (
  id INT(11) NOT NULL AUTO_INCREMENT,
  claimID INT(11) NOT NULL,
  playerOid BIGINT(20) DEFAULT NULL,
  playerName VARCHAR(45) DEFAULT NULL,
  permissionLevel INT(11) DEFAULT NULL,
  dateGiven DATETIME DEFAULT NULL,
  isactive TINYINT(1) DEFAULT 1,
  creationtimestamp TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  updatetimestamp DATETIME DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "claim_resource"
--
CREATE TABLE claim_resource (
  id INT(11) NOT NULL AUTO_INCREMENT,
  claimID INT(11) NOT NULL,
  itemID INT(11) NOT NULL,
  count INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "guild"
--
CREATE TABLE guild (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  faction INT(11) NOT NULL,
  motd VARCHAR(256) NOT NULL,
  omotd VARCHAR(256) NOT NULL,
  isactive TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "guild_member"
--
CREATE TABLE guild_member (
  id INT(11) NOT NULL AUTO_INCREMENT,
  guildID INT(11) NOT NULL,
  memberOid BIGINT(20) NOT NULL,
  name VARCHAR(32) DEFAULT NULL,
  rank INT(11) DEFAULT NULL,
  level INT(11) DEFAULT NULL,
  note VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Create table "guild_rank"
--
CREATE TABLE guild_rank (
  id INT(11) NOT NULL AUTO_INCREMENT,
  guildID INT(11) NOT NULL,
  rank INT(11) NOT NULL,
  name VARCHAR(45) NOT NULL,
  permissions VARCHAR(256) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;