--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.148.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2018-03-25 19:40:00
--



SET NAMES 'utf8';
USE `admin`;
--
-- -- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Inserting data into table claim
--
INSERT INTO claim(id, name, instance, locX, locY, locZ, claimType, owner, size, sizeZ, forSale, sellerName, cost, currency, purchaseItemReq, taxPaidUntil, claimItemTemplate, bondItemTemplate, bondPaidUntil, priority, isactive, creationtimestamp, updatetimestamp) VALUES
(21, 'AtavismBuildingAreaMW', 29, -128.98, 64.12, 143.01, 1, -1, 10, 10, 1, '', 1, 2, 0, NULL, -1, -1, NULL, 1, 1, '0000-00-00 00:00:00', '2018-03-25 19:32:13');

--
-- Updating data of table instance_template
--
UPDATE instance_template SET lastUpdate = '2016-07-11 11:03:22' WHERE id = 29;

--
-- Inserting data into table instance_template
--
INSERT INTO instance_template(id, island_name, template, administrator, category, status, subscription, public, password, rating, islandType, globalWaterHeight, createOnStartup, style, recommendedLevel, description, size, populationLimit, lastUpdate, dateCreated) VALUES
(39, 'InstanceSinglePlayer', '', 1, 1, 'Active', NULL, 1, '', 0, 1, -200, 1, '', 0, '', -1, 1, '2018-01-12 14:51:34', '0000-00-00 00:00:00'),
(40, 'InstanceGroup', '', 1, 1, 'Active', NULL, 1, '', 0, 2, -200, 1, '', 0, '', -1, 4, '2018-01-12 14:51:59', '0000-00-00 00:00:00'),
(41, 'Arena1v1', '', 1, 1, 'Active', NULL, 1, '', 0, 4, -200, 1, '', 0, '', -1, -1, '2018-01-12 14:53:09', '0000-00-00 00:00:00'),
(42, 'Arena2v2', '', 1, 1, 'Active', NULL, 1, '', 0, 4, -200, 1, '', 0, '', -1, -1, '2018-01-12 14:53:30', '0000-00-00 00:00:00'),
(43, 'SinglePlayerPrivate', '', 0, 1, 'Active', NULL, 1, '', 0, 3, -200, 1, '', 0, '', -1, -1, '2018-03-20 00:14:05', '0000-00-00 00:00:00'),
(44, 'GuildPrivate', '', 0, 1, 'Active', NULL, 1, '', 0, 5, -200, 0, '', 0, '', -1, -1, '2018-03-20 15:13:03', '0000-00-00 00:00:00');

--
-- Updating data of table island_portals
--
UPDATE island_portals SET portalType = 0, locX = -170, locY = 74, locZ = 154, displayID = 0 WHERE id = 7;

--
-- Inserting data into table island_portals
--
INSERT INTO island_portals(id, island, portalType, faction, locX, locY, locZ, orientX, orientY, orientZ, orientW, displayID, name, gameObject) VALUES
(21, 39, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 'spawn', NULL),
(22, 40, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 'spawn', NULL),
(23, 41, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 'spawn', NULL),
(24, 42, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 'spawn', NULL),
(25, 43, 0, 0, -170, 74, 154, 0, 0, 0, 1, 0, 'spawn', NULL),
(26, 44, 0, 0, -170, 74, 154, 0, 0, 0, 1, 0, 'spawn', NULL);
--
-- -- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;